import type * as React from 'react';
import type { SharedOrchestratorStageRun } from '@shared/orchestrator-stage-card-panel';
import type { AdminProjectItem, CategoryItem, CategoryStat } from '@/lib/admin-category-service';

export type AdminStageRunResponse = SharedOrchestratorStageRun & {
    updated_at?: string;
};

export type AdminLiveLogLevel = 'info' | 'warning' | 'success';
export type AdminCategorySortBy = 'name' | 'projects' | 'today' | 'downloads' | 'revenue' | 'rating' | 'active';

export type AdminBoardSection = {
    id: string;
    title: string;
    usage: string;
    description: string;
    open: boolean;
    onToggle: () => void;
    body: React.ReactNode;
    toggleTestId?: string;
    windowSize?: 'default' | 'wide' | 'full';
};

export type AdminDashboardSectionsConfigParams = {
    adminControlHubOpen: boolean;
    setAdminControlHubOpen: React.Dispatch<React.SetStateAction<boolean>>;
    systemSettings: any;
    dashboardAnalysis: any;
    setSystemSettingsPanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
    loadSystemSettings: () => void | Promise<void>;
    applyGlobalAutomaticMode: () => void | Promise<void>;
    healthOverviewOpen: boolean;
    setHealthOverviewOpen: React.Dispatch<React.SetStateAction<boolean>>;
    adminDashboardOverviewAssembly: any;
    autoConnectGraphPanelOpen: boolean;
    setAutoConnectGraphPanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
    adminAutoConnectGraphAssembly: any;
    customerOrchestratorPanelOpen: boolean;
    setCustomerOrchestratorPanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
    adminManualOrchestratorAssembly: any;
    adOrdersPanelOpen: boolean;
    setAdOrdersPanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
    adminAdOrdersAssembly: any;
    categoryPanelOpen: boolean;
    setCategoryPanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
    visibleCategories: CategoryItem[];
    sortedVisibleCategories: CategoryItem[];
    categoryStats: Record<number, CategoryStat>;
    categoryRecentProjects: Record<number, AdminProjectItem[]>;
    categoryMessage: string;
    categoryUpdatingId: number | null;
    categoryDeletingId: number | null;
    loadCategories: () => void | Promise<void>;
    updateCategory: (categoryId: number) => void | Promise<void>;
    cancelEditCategory: () => void;
    beginEditCategory: (category: CategoryItem) => void;
    deleteCategory: (category: CategoryItem) => void | Promise<void>;
    categoryName: string;
    categoryDescription: string;
    categoryCreating: boolean;
    hideEmptyCategories: boolean;
    categorySortBy: AdminCategorySortBy;
    setCategoryName: React.Dispatch<React.SetStateAction<string>>;
    setCategoryDescription: React.Dispatch<React.SetStateAction<string>>;
    createCategory: () => void | Promise<void>;
    setHideEmptyCategories: React.Dispatch<React.SetStateAction<boolean>>;
    setCategorySortBy: React.Dispatch<React.SetStateAction<AdminCategorySortBy>>;
    editingCategoryId: number | null;
    editingCategoryName: string;
    editingCategoryDescription: string;
    setEditingCategoryName: React.Dispatch<React.SetStateAction<string>>;
    setEditingCategoryDescription: React.Dispatch<React.SetStateAction<string>>;
    subscriptionMonitorPanelOpen: boolean;
    setSubscriptionMonitorPanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
    apiBaseUrl: string;
    costSimulatorPanelOpen: boolean;
    setCostSimulatorPanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
    costSimulatorForm: any;
    costSimulatorLoading: boolean;
    costSimulatorError: string | null;
    costSimulatorResult: any;
    updateCostSimulatorField: (key: string, value: string) => void;
    runCostSimulation: () => void | Promise<void>;
    quickLinksPanelOpen: boolean;
    setQuickLinksPanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
    llmControlPanelOpen: boolean;
    setLlmControlPanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
    llmPanelHeight: number;
    samplePanelOpen: boolean;
    setSamplePanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
    adminSampleProductsAssembly: any;
    liveLogsPanelOpen: boolean;
    setLiveLogsPanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
    liveLogs: any[];
    topProjectsPanelOpen: boolean;
    setTopProjectsPanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
    filteredTopProjects: any[];
    formatCurrency: (value: number) => string;
};

export type AdminPageActionsParams = {
    apiBaseUrl: string;
    setAdminUser: React.Dispatch<React.SetStateAction<{ username: string; email: string } | null>>;
    setAuthChecked: React.Dispatch<React.SetStateAction<boolean>>;
    setAuthStatusMessage: React.Dispatch<React.SetStateAction<string>>;
    setError: React.Dispatch<React.SetStateAction<string | null>>;
    setAdVideoOrders: React.Dispatch<React.SetStateAction<any[]>>;
    setAdVideoTotal: React.Dispatch<React.SetStateAction<number>>;
    setAdminStageRun: React.Dispatch<React.SetStateAction<AdminStageRunResponse | null>>;
    setAdminStageSubstepChecks: React.Dispatch<React.SetStateAction<Record<string, boolean>>>;
    adminStageRun: AdminStageRunResponse | null;
    adminStageNoteDraft: string;
    adminStageRevisionNote: string;
    adminStageSubstepChecks: Record<string, boolean>;
    pushLiveLog: (level: AdminLiveLogLevel, message: string) => void;
    setAdminStageRevisionNote: React.Dispatch<React.SetStateAction<string>>;
    setAdminStageNoteDraft: React.Dispatch<React.SetStateAction<string>>;
    setAdminStageUpdateLoading: React.Dispatch<React.SetStateAction<boolean>>;
    costSimulatorForm: Record<string, unknown>;
    setCostSimulatorLoading: React.Dispatch<React.SetStateAction<boolean>>;
    setCostSimulatorError: React.Dispatch<React.SetStateAction<string>>;
    setCostSimulatorResult: React.Dispatch<React.SetStateAction<any>>;
    setGeneratorModelOverrides: React.Dispatch<React.SetStateAction<Record<string, string>>>;
    generatorEnvKeyMap: Record<string, string[]>;
    updateSystemSettingValue: (key: string, value: string) => void;
};

export type AdminPageActionsResult = {
    handleAdminUnauthorized: (message?: string) => void;
    refreshAdminStageRun: (runId: string) => Promise<AdminStageRunResponse | null>;
    updateAdminStageStatus: (status: 'passed' | 'failed' | 'manual_correction') => Promise<void>;
    runCostSimulation: () => Promise<void>;
    applyGeneratorModelOverride: (profileId: string, modelName: string) => void;
};
