var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/marketplace/code-generator/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0u02_ro._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0x~mtp1.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~oj94g._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06hehg4._.js")
R.c("server/chunks/ssr/_0la7-wm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_marketplace_layout_tsx_0uq41z6._.js")
R.c("server/chunks/ssr/_next-internal_server_app_marketplace_code-generator_page_actions_12wr2h8.js")
R.m(9057)
module.exports=R.m(9057).exports
