/**
 * 설정 탭 ja/zh 오프라인 카탈로그 — EN API 번역 폴백 금지(혼용 방지).
 */
import type { SettingsUiText } from './settingsUiText';

export const SETTINGS_UI_JA: SettingsUiText = {
    headerTitle: '⚙️ 設定',
    intro: '主要設定をすばやく管理します。',
    sectionAccount: '👤 アカウント · プロフィール',
    sectionIncomingAlert: '🔔 着信アラート',
    sectionDevicePrep: '📱 端末の準備',
    sectionChatVoice: '🎧 チャット · 音声',
    sectionSorisae: '🐦 ソリセ AI',
    sectionManuals: '📖 使い方ガイド',
    sectionSecurity: '🔒 セキュリティ',
    country: '国',
    translationLanguage: '通訳/翻訳言語',
    profileLanguageLinkedHint: '国変更で自動連動 · チャット・VoIP・一般通話の既定',
    notSet: '未設定',
    saving: '保存中...',
    profileLinkLabel: 'プロフィール · 国 · 言語',
    profileLinkDesc: '通訳/翻訳の基本言語を変更',
    incomingAlertHint: '着信アラート方式',
    alertSound: '🔊 サウンド',
    alertVibrate: '📳 バイブ',
    alertSilent: '🔕 サイレント',
    micPermission: 'マイク権限',
    locationPermission: '位置情報権限',
    gpsService: 'GPSサービス',
    notificationPermission: '通知権限',
    granted: '許可済み',
    required: '必要',
    requestMic: '🎙️ マイク権限を要求',
    requestLocation: '📍 位置情報権限を要求',
    requestNotification: '🔔 通知権限を要求',
    openGpsSettings: '🛰️ GPS設定を開く (ON/OFF)',
    voipSpeakerDefault: '通話の既定出力: スピーカー',
    voipSpeakerOnDesc: '現在の既定: スピーカー ON',
    voipSpeakerOffDesc: '現在の既定: 受話器/イヤホン優先',
    voipSpeakerSetOn: '通話の既定出力をスピーカーに設定しました。',
    voipSpeakerSetOff: '通話の既定出力を受話器/イヤホン優先に設定しました。',
    currentAudioRoute: '現在のオーディオ経路',
    audioRouteLive: 'リアルタイム: スピーカー {speaker} · BT {bt}',
    refreshDeviceStatus: '端末権限の状態を更新しました。',
    refreshDeviceFailed: '端末権限の確認に失敗しました。',
    openSystemSettings: '⚙️ システム設定を開く',
    openVoipNotification: '📞 VoIP通知設定を開く',
    openBluetooth: '🎧 Bluetooth設定を開く (イヤホン)',
    refreshAudioRoute: '🔈 オーディオ経路を更新',
    refreshAudioRouteDone: 'オーディオ経路の状態を更新しました。',
    deviceChecking: '確認中...',
    refreshDevice: '🔄 状態を更新',
    speakerOn: 'ON',
    speakerOff: 'OFF',
    btConnected: '接続済み',
    btDisconnected: '未接続',
    autoListen: 'チャット自動リスン',
    autoListenDesc: '入室時に自動待機',
    readAloud: '受信メッセージを読み上げ',
    readAloudDesc: '相手メッセージ読み上げ',
    sorisaeFab: 'フローティングソリセボタン',
    sorisaeFabDesc: 'ホームボタン表示',
    manualsIntroKo: '機能ガイド',
    manualsIntroTranslated: '機能ガイド · {lang}',
    kwsAdvancedTitle: '🧠 詳細 · ウェイクワード検出',
    kwsSectionHint: 'ウェイクワード検出の詳細設定',
    kwsEngineLabel: '検出エンジン',
    kwsProviderVosk: '一般音声 (Vosk)',
    kwsProviderPorcupine: 'ウェイクワード専用 (Porcupine)',
    kwsModelFolder: '音声モデルフォルダ',
    kwsModelPlaceholder: '例: /sdcard/Download/vosk-model-small-ja',
    kwsPickModel: '📂 音声モデルファイルを選択',
    kwsPicking: '選択中...',
    kwsPicovoiceKey: 'Picovoiceアクセスキー',
    kwsPicovoicePlaceholder: 'Picovoiceで発行したキー',
    kwsKeywordFiles: 'ウェイクワードファイル (複数選択可)',
    kwsPickKeywords: '📂 ウェイクワードファイルを選択',
    kwsNoKeywordFiles: 'ウェイクワードファイルが選択されていません。',
    kwsSave: 'ウェイクワード設定を保存',
    kwsSaving: '保存中...',
    kwsSaved: 'ウェイクワード設定を保存しました。',
    kwsSaveFailed: 'ウェイクワード設定の保存に失敗しました。',
    kwsVoskPathRequired: 'Voskモデルフォルダのパスを入力してください。',
    kwsPicovoiceKeyRequired: 'Picovoiceアクセスキーを入力してください。',
    kwsKeywordRequired: 'ウェイクワードファイルを1つ以上選択してください。',
    kwsPpnRequired: '.ppnウェイクワードファイルを選択してください。',
    kwsPickPpnFailed: 'ウェイクワードファイルの選択に失敗しました。',
    kwsPpnSelected: 'ウェイクワードファイル {count} 件を選択しました。',
    passwordChange: 'パスワード変更',
    loginRequiredToChange: '変更するにはログインしてください。',
    unsupportedLanguage: 'サポートされていない言語です。',
    countrySavedSuccess: '国を保存しました。',
    countrySaveFailed: '国の保存に失敗しました。',
    languageSavedSuccess: '通訳/翻訳言語を保存しました。',
    languageSaveFailed: '言語の保存に失敗しました。',
};

export const SETTINGS_UI_ZH: SettingsUiText = {
    headerTitle: '⚙️ 设置',
    intro: '快速管理核心设置。',
    sectionAccount: '👤 账户 · 个人资料',
    sectionIncomingAlert: '🔔 收到警报',
    sectionDevicePrep: '📱 设备就绪',
    sectionChatVoice: '🎧 聊天 · 语音',
    sectionSorisae: '🐦 索里塞 AI',
    sectionManuals: '📖 使用说明',
    sectionSecurity: '🔒 安全',
    country: '国家',
    translationLanguage: '传译/翻译语言',
    profileLanguageLinkedHint: '随国家自动联动 · 聊天/VoIP/普通通话默认',
    notSet: '未设置',
    saving: '保存中...',
    profileLinkLabel: '个人资料 · 国家 · 语言',
    profileLinkDesc: '更改传译/翻译默认语言',
    incomingAlertHint: '来电提醒方式',
    alertSound: '🔊 声音',
    alertVibrate: '📳 振动',
    alertSilent: '🔕 静音',
    micPermission: '麦克风权限',
    locationPermission: '位置权限',
    gpsService: 'GPS 服务',
    notificationPermission: '通知权限',
    granted: '已允许',
    required: '需要',
    requestMic: '🎙️ 请求麦克风权限',
    requestLocation: '📍 请求位置权限',
    requestNotification: '🔔 请求通知权限',
    openGpsSettings: '🛰️ 打开 GPS 设置 (开/关)',
    voipSpeakerDefault: '通话默认输出：扬声器',
    voipSpeakerOnDesc: '当前默认：扬声器开',
    voipSpeakerOffDesc: '当前默认：听筒/耳机优先',
    voipSpeakerSetOn: '通话默认输出已设为扬声器。',
    voipSpeakerSetOff: '通话默认输出已设为听筒/耳机优先。',
    currentAudioRoute: '当前音频路径',
    audioRouteLive: '实时：扬声器 {speaker} · 蓝牙 {bt}',
    refreshDeviceStatus: '已刷新设备权限状态。',
    refreshDeviceFailed: '检查设备权限失败。',
    openSystemSettings: '⚙️ 打开系统设置',
    openVoipNotification: '📞 打开 VoIP 通知设置',
    openBluetooth: '🎧 打开蓝牙设置（耳机）',
    refreshAudioRoute: '🔈 刷新音频路径',
    refreshAudioRouteDone: '已刷新音频路径状态。',
    deviceChecking: '检查中...',
    refreshDevice: '🔄 刷新状态',
    speakerOn: '开',
    speakerOff: '关',
    btConnected: '已连接',
    btDisconnected: '未连接',
    autoListen: '聊天自动监听',
    autoListenDesc: '入房后自动待机',
    readAloud: '朗读收到的消息',
    readAloudDesc: '朗读对方消息',
    sorisaeFab: '浮动索里塞按钮',
    sorisaeFabDesc: '显示首页按钮',
    manualsIntroKo: '功能指南',
    manualsIntroTranslated: '功能指南 · {lang}',
    kwsAdvancedTitle: '🧠 高级 · 唤醒词检测',
    kwsSectionHint: '唤醒词检测高级设置',
    kwsEngineLabel: '检测引擎',
    kwsProviderVosk: '通用语音 (Vosk)',
    kwsProviderPorcupine: '唤醒词专用 (Porcupine)',
    kwsModelFolder: '语音模型文件夹',
    kwsModelPlaceholder: '例：/sdcard/Download/vosk-model-small-zh',
    kwsPickModel: '📂 选择语音模型文件',
    kwsPicking: '选择中...',
    kwsPicovoiceKey: 'Picovoice 访问密钥',
    kwsPicovoicePlaceholder: 'Picovoice 发放的密钥',
    kwsKeywordFiles: '唤醒词文件（可多选）',
    kwsPickKeywords: '📂 选择唤醒词文件',
    kwsNoKeywordFiles: '未选择唤醒词文件。',
    kwsSave: '保存唤醒词设置',
    kwsSaving: '保存中...',
    kwsSaved: '唤醒词设置已保存。',
    kwsSaveFailed: '保存唤醒词设置失败。',
    kwsVoskPathRequired: '请输入 Vosk 模型文件夹路径。',
    kwsPicovoiceKeyRequired: '请输入 Picovoice 访问密钥。',
    kwsKeywordRequired: '请至少选择一个唤醒词文件。',
    kwsPpnRequired: '请选择 .ppn 唤醒词文件。',
    kwsPickPpnFailed: '选择唤醒词文件失败。',
    kwsPpnSelected: '已选择 {count} 个唤醒词文件。',
    passwordChange: '更改密码',
    loginRequiredToChange: '请先登录后再更改。',
    unsupportedLanguage: '不支持的语言。',
    countrySavedSuccess: '国家已保存。',
    countrySaveFailed: '国家保存失败。',
    languageSavedSuccess: '口译/翻译语言已保存。',
    languageSaveFailed: '语言保存失败。',
};
