var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/login/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__04leepa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0h0nonc.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~oj94g._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06hehg4._.js")
R.c("server/chunks/ssr/_0la7-wm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_admin_layout_tsx_0yjsw7q._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_login_page_actions_01851m~.js")
R.m(46580)
module.exports=R.m(46580).exports
