/**
 * UI_LANGS_FOR_HELP — 도움말 패널에서 사용할 언어 목록 (50개국어)
 * 기존 page.tsx의 UI_LANGS와 동일 데이터를 독립 모듈로 분리하여
 * HelpPanel이 page.tsx에 의존하지 않도록 합니다.
 */

export const UI_LANGS_FOR_HELP = [
    { label: '한국어', code: 'ko' },
    { label: 'English', code: 'en' },
    { label: '日本語', code: 'ja' },
    { label: '中文(简体)', code: 'zh' },
    { label: '繁體中文', code: 'zh-tw' },
    { label: 'Español', code: 'es' },
    { label: 'Français', code: 'fr' },
    { label: 'Deutsch', code: 'de' },
    { label: 'Português', code: 'pt' },
    { label: 'Italiano', code: 'it' },
    { label: 'Русский', code: 'ru' },
    { label: 'Українська', code: 'uk' },
    { label: 'Polski', code: 'pl' },
    { label: 'Nederlands', code: 'nl' },
    { label: 'Svenska', code: 'sv' },
    { label: 'Norsk', code: 'no' },
    { label: 'Dansk', code: 'da' },
    { label: 'Suomi', code: 'fi' },
    { label: 'Čeština', code: 'cs' },
    { label: 'Slovenčina', code: 'sk' },
    { label: 'Magyar', code: 'hu' },
    { label: 'Română', code: 'ro' },
    { label: 'Български', code: 'bg' },
    { label: 'Ελληνικά', code: 'el' },
    { label: 'Türkçe', code: 'tr' },
    { label: 'العربية', code: 'ar' },
    { label: 'فارسی', code: 'fa' },
    { label: 'עברית', code: 'he' },
    { label: 'हिन्दी', code: 'hi' },
    { label: 'বাংলা', code: 'bn' },
    { label: 'اردو', code: 'ur' },
    { label: 'தமிழ்', code: 'ta' },
    { label: 'తెలుగు', code: 'te' },
    { label: 'ภาษาไทย', code: 'th' },
    { label: 'Tiếng Việt', code: 'vi' },
    { label: 'Indonesia', code: 'id' },
    { label: 'Melayu', code: 'ms' },
    { label: 'Filipino', code: 'tl' },
    { label: 'Kiswahili', code: 'sw' },
    { label: 'አማርኛ', code: 'am' },
    { label: 'isiZulu', code: 'zu' },
    { label: 'Afrikaans', code: 'af' },
    { label: 'Yorùbá', code: 'yo' },
    { label: 'Igbo', code: 'ig' },
    { label: 'Hausa', code: 'ha' },
    { label: 'Монгол', code: 'mn' },
    { label: 'Қазақша', code: 'kk' },
    { label: 'Oʻzbekcha', code: 'uz' },
    { label: 'Српски', code: 'sr' },
    { label: 'Hrvatski', code: 'hr' },
] as const;
