from pathlib import Path
import json

import pytest

from backend.llm.orchestrator import _compat_write_auxiliary_outputs, _compat_write_manifest, _strip_generated_id_headers


def test_compat_write_manifest_preserves_existing_non_empty_generated_file(tmp_path: Path) -> None:
    target = tmp_path / "app" / "main.py"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("print('generated by multi-generator')\n", encoding="utf-8")

    written_files = _compat_write_manifest(
        tmp_path,
        [
            {
                "path": "app/main.py",
                "content": "print('compat fallback')\n",
            }
        ],
    )

    assert written_files == ["app/main.py"]
    assert target.read_text(encoding="utf-8") == "print('generated by multi-generator')\n"


def test_compat_write_auxiliary_outputs_generates_id_autolink_documents(tmp_path: Path) -> None:
    written_files = [
        "app/main.py",
        "app/routes.py",
        "app/services/__init__.py",
        "app/services/runtime_service.py",
    ]
    outputs = _compat_write_auxiliary_outputs(
        tmp_path,
        task="ID linked output generation",
        project_name="id-link-check",
        mode="code",
        validation_profile="python_fastapi",
        written_files=written_files,
        anchor_path="app/main.py",
        semantic_audit_score=96,
        semantic_audit_ok=True,
        target_patch_registry_snapshot={
            "target_file_ids": ["FILE-APP-MAIN-PY"],
            "target_section_ids": ["SECTION-APP-MAIN-PY-MAIN"],
            "target_feature_ids": ["FEATURE-APP-MAIN-PY-RUNTIME"],
            "target_chunk_ids": ["CHUNK-APP-MAIN-PY-001"],
            "failure_tags": [],
            "repair_tags": [],
        },
    )

    auto_link_map_path = tmp_path / str(outputs["auto_link_map_path"])
    section_id_index_path = tmp_path / str(outputs["section_id_index_path"])

    assert auto_link_map_path.exists()
    assert section_id_index_path.exists()

    auto_link_map = json.loads(auto_link_map_path.read_text(encoding="utf-8"))
    assert auto_link_map["auto_connect_policy"]["self_link_enabled"] is True
    assert any(item["path"] == "app/main.py" for item in auto_link_map["links"])

    section_index = section_id_index_path.read_text(encoding="utf-8")
    assert "SECTION-ID" in section_index
    assert "app/main.py" in section_index


def test_compat_write_manifest_overwrites_stale_service_package_exports(tmp_path: Path) -> None:
    target = tmp_path / "app" / "services" / "__init__.py"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        "from app.services.runtime_service import build_health_payload, build_runtime_summary\n\n"
        "__all__ = ['build_health_payload', 'build_runtime_summary']\n",
        encoding="utf-8",
    )

    _compat_write_manifest(
        tmp_path,
        [
            {
                "path": "app/services/__init__.py",
                "content": (
                    "from app.services.runtime_service import build_runtime_payload, summarize_health\n\n"
                    "__all__ = ['build_runtime_payload', 'summarize_health']\n"
                ),
            }
        ],
    )

    updated = target.read_text(encoding="utf-8")
    assert "build_runtime_payload" in updated
    assert "summarize_health" in updated
    assert "build_health_payload" not in updated


def test_compat_write_manifest_overwrites_stale_runtime_service_contract(tmp_path: Path) -> None:
    target = tmp_path / "app" / "services" / "runtime_service.py"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        "def build_runtime_summary() -> dict:\n"
        "    return {'status': 'ok'}\n\n"
        "def build_health_payload() -> dict:\n"
        "    return {'status': 'ok'}\n",
        encoding="utf-8",
    )

    _compat_write_manifest(
        tmp_path,
        [
            {
                "path": "app/services/runtime_service.py",
                "content": (
                    "def build_runtime_payload(runtime_mode: str = 'default') -> dict:\n"
                    "    return {'runtime_mode': runtime_mode}\n\n"
                    "def list_endpoints() -> list[str]:\n"
                    "    return ['/health']\n\n"
                    "def summarize_health() -> dict:\n"
                    "    return {'status': 'ok'}\n"
                ),
            }
        ],
    )

    updated = target.read_text(encoding="utf-8")
    assert "def build_runtime_payload" in updated
    assert "def list_endpoints" in updated
    assert "def summarize_health" in updated
    assert "def build_runtime_summary" not in updated


def test_compat_write_manifest_overwrites_stale_app_main_runtime_entrypoint(tmp_path: Path) -> None:
    target = tmp_path / "app" / "main.py"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        "from fastapi import FastAPI\n\n"
        "from app.api.routes.health import router as health_router\n"
        "from app.services.runtime_service import build_runtime_summary\n\n"
        "app = FastAPI()\n"
        "app.include_router(health_router)\n",
        encoding="utf-8",
    )

    _compat_write_manifest(
        tmp_path,
        [
            {
                "path": "app/main.py",
                "content": (
                    "from fastapi import FastAPI\n"
                    "from app.services import build_runtime_payload, summarize_health\n\n"
                    "def create_application() -> FastAPI:\n"
                    "    app = FastAPI()\n"
                    "    return app\n\n"
                    "app = create_application()\n"
                ),
            }
        ],
    )

    updated = target.read_text(encoding="utf-8")
    assert "def create_application()" in updated
    assert "build_runtime_payload" in updated
    assert "summarize_health" in updated
    assert "build_runtime_summary" not in updated


def test_compat_write_manifest_overwrites_stale_empty_authoritative_bridge_file(tmp_path: Path) -> None:
    target = tmp_path / "app" / "__init__.py"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        "from app.main import app, create_application\n"
        "from app.services import build_runtime_payload\n\n"
        "__all__ = ['app', 'create_application', 'build_runtime_payload']\n",
        encoding="utf-8",
    )

    _compat_write_manifest(
        tmp_path,
        [
            {
                "path": "app/__init__.py",
                "content": "",
            }
        ],
    )

    updated = target.read_text(encoding="utf-8")
    assert "create_application" not in updated
    assert "build_runtime_payload" not in updated


@pytest.mark.parametrize(
    "relative_path",
    [
        "app/api/routes/__init__.py",
        "ai/__init__.py",
        "backend/app/api/routes/__init__.py",
    ],
)
def test_compat_write_manifest_overwrites_other_stale_empty_authoritative_bridge_files(
    tmp_path: Path,
    relative_path: str,
) -> None:
    target = tmp_path / relative_path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        "from legacy.module import stale_export\n\n"
        "__all__ = ['stale_export']\n",
        encoding="utf-8",
    )

    _compat_write_manifest(
        tmp_path,
        [
            {
                "path": relative_path,
                "content": "",
            }
        ],
    )

    updated = target.read_text(encoding="utf-8")
    assert _strip_generated_id_headers(updated).strip() == ""


@pytest.mark.parametrize(
    ("relative_path", "existing_content", "rendered_content", "expected_markers", "forbidden_markers"),
    [
        (
            "app/__init__.py",
            "from app.main import app\n\n__all__ = ['app']\n",
            (
                "from app.main import app, create_application\n"
                "from app.services import build_runtime_payload, build_catalog_snapshot\n\n"
                "__all__ = ['app', 'create_application', 'build_runtime_payload', 'build_catalog_snapshot']\n"
            ),
            ["from app.main import app, create_application", "build_runtime_payload", "create_application"],
            ["__all__ = ['app']"],
        ),
        (
            "app/routes.py",
            "from fastapi import APIRouter\n\nrouter = APIRouter()\n\n@router.get('/health')\ndef health():\n    return {'status': 'ok'}\n",
            (
                "from fastapi import APIRouter\n"
                "from app.services import build_runtime_payload, list_endpoints, summarize_health, build_domain_snapshot\n"
                "from app.order_profile import get_order_profile, get_flow_step, list_flow_steps\n"
                "from app.diagnostics import build_diagnostic_report, validate_runtime_payload\n\n"
                "router = APIRouter()\n\n"
                "@router.get('/health')\n"
                "def health():\n    return summarize_health()\n\n"
                "@router.get('/order-profile')\n"
                "def order_profile():\n    return get_order_profile()\n\n"
                "@router.get('/report')\n"
                "def report():\n    return build_diagnostic_report()\n\n"
                "@router.post('/diagnose')\n"
                "def diagnose(payload: dict | None = None):\n    return {'status': 'accepted'}\n"
            ),
            ["@router.get('/order-profile')", "@router.get('/report')", "@router.post('/diagnose')"],
            ["return {'status': 'ok'}"],
        ),
        (
            "app/auth_routes.py",
            "from fastapi import APIRouter\n\nauth_router = APIRouter()\n\n@auth_router.post('/login')\ndef login():\n    return {'ok': True}\n",
            (
                "from fastapi import APIRouter, HTTPException\n"
                "from backend.core.auth import create_access_token, decode_access_token, get_auth_settings\n\n"
                "auth_router = APIRouter(prefix='/auth', tags=['auth'])\n\n"
                "@auth_router.get('/settings')\n"
                "def auth_settings():\n    return get_auth_settings()\n\n"
                "@auth_router.post('/token')\n"
                "def issue_token(payload: dict | None = None):\n    return {'access_token': 'token'}\n\n"
                "@auth_router.post('/validate')\n"
                "def validate_token(payload: dict | None = None):\n    raise HTTPException(status_code=400, detail='token is required')\n"
            ),
            ["@auth_router.get('/settings')", "@auth_router.post('/token')", "@auth_router.post('/validate')"],
            ["@auth_router.post('/login')"],
        ),
        (
            "app/ops_routes.py",
            (
                "from fastapi import APIRouter\n"
                "from fastapi.responses import PlainTextResponse\n\n"
                "ops_router = APIRouter(tags=['ops'])\n\n"
                "@ops_router.get('/ops/health')\n"
                "def ops_health():\n    return {'status': 'ok'}\n\n"
                "@ops_router.get('/metrics', response_class=PlainTextResponse)\n"
                "def metrics():\n    return 'commerce_providers_up 1\\n'\n"
            ),
            (
                "from fastapi.responses import PlainTextResponse\n"
                "from fastapi import APIRouter\n"
                "from backend.app.external_adapters.status_client import fetch_upstream_status\n\n"
                "ops_router = APIRouter(prefix='/ops', tags=['ops'])\n\n"
                "@ops_router.get('/status')\n"
                "def ops_status():\n    provider = fetch_upstream_status()\n    return {'status': 'ok', 'provider_status': provider}\n\n"
                "@ops_router.get('/health')\n"
                "def ops_health():\n    return ops_status()\n\n"
                "@ops_router.get('/logs')\n"
                "def ops_logs():\n    return {'items': [], 'count': 0}\n\n"
                "@ops_router.get('/metrics', response_class=PlainTextResponse)\n"
                "def metrics():\n    return 'customer_provider_up 1\\n'\n"
            ),
            ["@ops_router.get('/status')", "@ops_router.get('/health')", "@ops_router.get('/logs')", "customer_provider_up"],
            ["@ops_router.get('/ops/health')", "commerce_providers_up"],
        ),
        (
            "backend/core/__init__.py",
            "from backend.core.runtime import build_runtime_summary\n",
            (
                "from backend.core.runtime import build_scaffold_runtime\n"
                "from backend.core.flow_registry import list_registered_steps, find_registered_step\n\n"
                "__all__ = ['build_scaffold_runtime', 'list_registered_steps', 'find_registered_step']\n"
            ),
            ["build_scaffold_runtime", "list_registered_steps", "find_registered_step"],
            ["build_runtime_summary"],
        ),
        (
            "backend/service/application_service.py",
            "def build_summary() -> dict:\n    return {'layer': 'service'}\n",
            (
                "def build_service_overview() -> dict:\n"
                "    return {\n"
                "        'sources': [],\n"
                "        'flow_steps': [],\n"
                "        'publish_payload': {},\n"
                "        'layer': 'service',\n"
                "    }\n"
            ),
            ["def build_service_overview()", "'flow_steps'", "'publish_payload'", "'layer': 'service'"],
            ["def build_summary()"],
        ),
        (
            "backend/api/router.py",
            "def router_health() -> dict:\n    return {'status': 'ok'}\n",
            (
                "def get_router_snapshot() -> dict:\n"
                "    return {'layer': 'api', 'trace_lookup': {}}\n\n"
                "def get_catalog_runtime_snapshot() -> dict:\n"
                "    return {'catalog': {}, 'order_workflow': {}}\n\n"
                "def get_publish_readiness_snapshot() -> dict:\n"
                "    return {'publish_payload': {}, 'operations_catalog': {}}\n"
            ),
            ["def get_router_snapshot()", "def get_catalog_runtime_snapshot()", "def get_publish_readiness_snapshot()", "trace_lookup"],
            ["def router_health()"],
        ),
    ],
)
def test_compat_write_manifest_overwrites_stale_profile_entrypoints(
    tmp_path: Path,
    relative_path: str,
    existing_content: str,
    rendered_content: str,
    expected_markers: list[str],
    forbidden_markers: list[str],
) -> None:
    target = tmp_path / relative_path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(existing_content, encoding="utf-8")

    _compat_write_manifest(
        tmp_path,
        [
            {
                "path": relative_path,
                "content": rendered_content,
            }
        ],
    )

    updated = target.read_text(encoding="utf-8")
    for marker in expected_markers:
        assert marker in updated
    for marker in forbidden_markers:
        assert marker not in updated
