import './globals.css';
import type { ReactNode } from 'react';
import { IBM_Plex_Mono, Space_Grotesk } from 'next/font/google';

const display = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-display',
});

const mono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-mono',
});

export const metadata = {
  title: '오케스트레이터-자가개선-실험-즉시-실행-원본-대상-경로-C-Use-88b347d566-nextjs_react',
  description: 'Operations canvas generated by the deterministic scaffold.',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${display.variable} ${mono.variable}`}>
        <div className="shell">{children}</div>
      </body>
    </html>
  );
}
