// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[...adminOnly]" | "/admin" | "/admin/carbon" | "/admin/docs-viewer" | "/admin/llm" | "/admin/login" | "/admin/recovery" | "/admin/regional" | "/admin/subscription-monitor" | "/admin/tourism-review" | "/admin/users" | "/marketplace" | "/marketplace/[id]" | "/marketplace/code-generator" | "/marketplace/exp/game" | "/marketplace/exp/iot" | "/marketplace/exp/music" | "/marketplace/exp/predict" | "/marketplace/exp/quantum" | "/marketplace/exp/security" | "/marketplace/metrics" | "/marketplace/ml-detectors" | "/marketplace/nadotongryoksa" | "/marketplace/orchestrator" | "/marketplace/subscription" | "/marketplace/worldlinco" | "/privacy" | "/sorisae-dashboard" | "/terms"
type AppRouteHandlerRoutes = "/.well-known/webauthn" | "/api/admin/system-settings" | "/api/admin/users" | "/api/admin/users/[userId]" | "/api/admin/worldlinco-billing-policy" | "/api/admin/worldlinco-tourism-promo" | "/api/admin/worldlinco-tuning" | "/api/backend-proxy/[...path]" | "/api/llm/autonomous/chat" | "/api/llm/autonomous/session/[sessionId]" | "/api/llm/orchestrate/chat" | "/api/llm/voice/orchestrate" | "/api/llm/voice/synthesize" | "/api/marketplace/customer-orchestrate/stage-runs" | "/api/marketplace/customer-orchestrate/stage-runs/[runId]" | "/api/marketplace/download-product" | "/api/marketplace/face-recognition/status" | "/api/marketplace/metrics/prometheus" | "/api/marketplace/metrics/summary" | "/api/marketplace/ml-detectors/status" | "/api/proxy"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/marketplace"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]" | "/api/backend-proxy/[[...path]]" | "/docs" | "/openapi.json"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/.well-known/webauthn": {}
  "/[...adminOnly]": { "adminOnly": string[]; }
  "/admin": {}
  "/admin/carbon": {}
  "/admin/docs-viewer": {}
  "/admin/llm": {}
  "/admin/login": {}
  "/admin/recovery": {}
  "/admin/regional": {}
  "/admin/subscription-monitor": {}
  "/admin/tourism-review": {}
  "/admin/users": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/api/admin/system-settings": {}
  "/api/admin/users": {}
  "/api/admin/users/[userId]": { "userId": string; }
  "/api/admin/worldlinco-billing-policy": {}
  "/api/admin/worldlinco-tourism-promo": {}
  "/api/admin/worldlinco-tuning": {}
  "/api/backend-proxy/[...path]": { "path": string[]; }
  "/api/backend-proxy/[[...path]]": { "path"?: string[]; }
  "/api/llm/autonomous/chat": {}
  "/api/llm/autonomous/session/[sessionId]": { "sessionId": string; }
  "/api/llm/orchestrate/chat": {}
  "/api/llm/voice/orchestrate": {}
  "/api/llm/voice/synthesize": {}
  "/api/marketplace/customer-orchestrate/stage-runs": {}
  "/api/marketplace/customer-orchestrate/stage-runs/[runId]": { "runId": string; }
  "/api/marketplace/download-product": {}
  "/api/marketplace/face-recognition/status": {}
  "/api/marketplace/metrics/prometheus": {}
  "/api/marketplace/metrics/summary": {}
  "/api/marketplace/ml-detectors/status": {}
  "/api/proxy": {}
  "/docs": {}
  "/marketplace": {}
  "/marketplace/[id]": { "id": string; }
  "/marketplace/code-generator": {}
  "/marketplace/exp/game": {}
  "/marketplace/exp/iot": {}
  "/marketplace/exp/music": {}
  "/marketplace/exp/predict": {}
  "/marketplace/exp/quantum": {}
  "/marketplace/exp/security": {}
  "/marketplace/metrics": {}
  "/marketplace/ml-detectors": {}
  "/marketplace/nadotongryoksa": {}
  "/marketplace/orchestrator": {}
  "/marketplace/subscription": {}
  "/marketplace/worldlinco": {}
  "/openapi.json": {}
  "/privacy": {}
  "/sorisae-dashboard": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/marketplace": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
