// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/[...adminOnly]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[...adminOnly]">> = Specific
  const handler = {} as typeof import("../../../app/[...adminOnly]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/carbon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/carbon">> = Specific
  const handler = {} as typeof import("../../../app/admin/carbon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/docs-viewer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/docs-viewer">> = Specific
  const handler = {} as typeof import("../../../app/admin/docs-viewer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/llm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/llm">> = Specific
  const handler = {} as typeof import("../../../app/admin/llm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../../app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/recovery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/recovery">> = Specific
  const handler = {} as typeof import("../../../app/admin/recovery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/regional/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/regional">> = Specific
  const handler = {} as typeof import("../../../app/admin/regional/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/subscription-monitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/subscription-monitor">> = Specific
  const handler = {} as typeof import("../../../app/admin/subscription-monitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/tourism-review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tourism-review">> = Specific
  const handler = {} as typeof import("../../../app/admin/tourism-review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/marketplace/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/[id]">> = Specific
  const handler = {} as typeof import("../../../app/marketplace/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/marketplace/code-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/code-generator">> = Specific
  const handler = {} as typeof import("../../../app/marketplace/code-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/marketplace/exp/game/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/exp/game">> = Specific
  const handler = {} as typeof import("../../../app/marketplace/exp/game/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/marketplace/exp/iot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/exp/iot">> = Specific
  const handler = {} as typeof import("../../../app/marketplace/exp/iot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/marketplace/exp/music/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/exp/music">> = Specific
  const handler = {} as typeof import("../../../app/marketplace/exp/music/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/marketplace/exp/predict/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/exp/predict">> = Specific
  const handler = {} as typeof import("../../../app/marketplace/exp/predict/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/marketplace/exp/quantum/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/exp/quantum">> = Specific
  const handler = {} as typeof import("../../../app/marketplace/exp/quantum/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/marketplace/exp/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/exp/security">> = Specific
  const handler = {} as typeof import("../../../app/marketplace/exp/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/marketplace/metrics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/metrics">> = Specific
  const handler = {} as typeof import("../../../app/marketplace/metrics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/marketplace/ml-detectors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/ml-detectors">> = Specific
  const handler = {} as typeof import("../../../app/marketplace/ml-detectors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/marketplace/nadotongryoksa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/nadotongryoksa">> = Specific
  const handler = {} as typeof import("../../../app/marketplace/nadotongryoksa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/marketplace/orchestrator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/orchestrator">> = Specific
  const handler = {} as typeof import("../../../app/marketplace/orchestrator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/marketplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace">> = Specific
  const handler = {} as typeof import("../../../app/marketplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/marketplace/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/subscription">> = Specific
  const handler = {} as typeof import("../../../app/marketplace/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/marketplace/worldlinco/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/worldlinco">> = Specific
  const handler = {} as typeof import("../../../app/marketplace/worldlinco/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sorisae-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sorisae-dashboard">> = Specific
  const handler = {} as typeof import("../../../app/sorisae-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/.well-known/webauthn/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/.well-known/webauthn">> = Specific
  const handler = {} as typeof import("../../../app/.well-known/webauthn/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/system-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system-settings">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/system-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/users/[userId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[userId]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/users/[userId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/worldlinco-billing-policy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/worldlinco-billing-policy">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/worldlinco-billing-policy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/worldlinco-tourism-promo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/worldlinco-tourism-promo">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/worldlinco-tourism-promo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/worldlinco-tuning/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/worldlinco-tuning">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/worldlinco-tuning/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/backend-proxy/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend-proxy/[...path]">> = Specific
  const handler = {} as typeof import("../../../app/api/backend-proxy/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/llm/autonomous/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/llm/autonomous/chat">> = Specific
  const handler = {} as typeof import("../../../app/api/llm/autonomous/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/llm/autonomous/session/[sessionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/llm/autonomous/session/[sessionId]">> = Specific
  const handler = {} as typeof import("../../../app/api/llm/autonomous/session/[sessionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/llm/orchestrate/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/llm/orchestrate/chat">> = Specific
  const handler = {} as typeof import("../../../app/api/llm/orchestrate/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/llm/voice/orchestrate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/llm/voice/orchestrate">> = Specific
  const handler = {} as typeof import("../../../app/api/llm/voice/orchestrate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/llm/voice/synthesize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/llm/voice/synthesize">> = Specific
  const handler = {} as typeof import("../../../app/api/llm/voice/synthesize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/marketplace/customer-orchestrate/stage-runs/[runId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketplace/customer-orchestrate/stage-runs/[runId]">> = Specific
  const handler = {} as typeof import("../../../app/api/marketplace/customer-orchestrate/stage-runs/[runId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/marketplace/customer-orchestrate/stage-runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketplace/customer-orchestrate/stage-runs">> = Specific
  const handler = {} as typeof import("../../../app/api/marketplace/customer-orchestrate/stage-runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/marketplace/download-product/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketplace/download-product">> = Specific
  const handler = {} as typeof import("../../../app/api/marketplace/download-product/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/marketplace/face-recognition/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketplace/face-recognition/status">> = Specific
  const handler = {} as typeof import("../../../app/api/marketplace/face-recognition/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/marketplace/metrics/prometheus/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketplace/metrics/prometheus">> = Specific
  const handler = {} as typeof import("../../../app/api/marketplace/metrics/prometheus/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/marketplace/metrics/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketplace/metrics/summary">> = Specific
  const handler = {} as typeof import("../../../app/api/marketplace/metrics/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/marketplace/ml-detectors/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketplace/ml-detectors/status">> = Specific
  const handler = {} as typeof import("../../../app/api/marketplace/ml-detectors/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/proxy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proxy">> = Specific
  const handler = {} as typeof import("../../../app/api/proxy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/marketplace/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/marketplace">> = Specific
  const handler = {} as typeof import("../../../app/marketplace/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
