var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/marketplace/subscription/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0s1ova2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0~h6my..js")
R.c("server/chunks/ssr/[root-of-the-server]__0~oj94g._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06hehg4._.js")
R.c("server/chunks/ssr/_0la7-wm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_marketplace_layout_tsx_0uq41z6._.js")
R.c("server/chunks/ssr/_next-internal_server_app_marketplace_subscription_page_actions_0mlx7mp.js")
R.m(12207)
module.exports=R.m(12207).exports
