// App.tsx 에서 분리한 StyleSheet (정적). 색상 토큰만 appTheme 에서 import.
import { StyleSheet } from 'react-native';
import { C } from './src/app/appTheme';

export const styles = StyleSheet.create({
    skyBg: { flex: 1 },
    root: { flex: 1, backgroundColor: 'transparent' },
    scroll: { padding: 10, paddingBottom: 108 },
    bottomTabBar: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 200,
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        borderTopWidth: 1,
        borderTopColor: '#E3EAF3',
        paddingTop: 6,
        shadowColor: '#0B2E5E',
        shadowOpacity: 0.08,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: -4 },
        elevation: 12,
    },
    bottomTabItem: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 2, paddingVertical: 4 },
    bottomTabIcon: { fontSize: 20, color: '#8A97A8' },
    bottomTabLabel: { fontSize: 11, fontWeight: '600', color: '#8A97A8' },
    // ── 액션 타일 그리드 (APP_DESIGN 0-6 · 태스크 우선) ──
    actionTileGrid: { gap: 10, marginTop: 4 },
    actionTileGrid2: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 12, marginTop: 4 },
    actionTileHalf: { width: '48%', paddingHorizontal: 12, gap: 10 },
    gridTile: {
        width: '48%',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        paddingVertical: 18,
        paddingHorizontal: 10,
        borderWidth: 1,
        borderColor: '#E8EEF6',
        shadowColor: '#0B2E5E',
        shadowOpacity: 0.06,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        elevation: 2,
    },
    gridTileActive: { borderColor: '#1E6FE0', borderWidth: 2 },
    gridTileIcon: { width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
    gridTileEmoji: { fontSize: 24 },
    gridTileLabel: { fontSize: 16, fontWeight: '800', color: '#1A1F36', textAlign: 'center' },
    gridTileSub: { fontSize: 12, color: '#6B7280', marginTop: 3, textAlign: 'center' },
    hubHeroRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 14, marginTop: 2 },
    hubHeroIcon: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
    hubHeroEmoji: { fontSize: 22 },
    hubHeroTitle: { flex: 1, fontSize: 16, fontWeight: '800', color: '#1A1F36' },
    voipTileList: { gap: 12, marginTop: 4 },
    voipTile: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        paddingVertical: 16,
        paddingHorizontal: 16,
        borderWidth: 1,
        borderColor: '#E8EEF6',
        shadowColor: '#0B2E5E',
        shadowOpacity: 0.06,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        elevation: 2,
    },
    voipTileChevron: { fontSize: 26, color: '#9aa6b8', fontWeight: '400', marginLeft: 4 },
    voipTabRow: { flexDirection: 'row', gap: 8, marginTop: 4, marginBottom: 10 },
    voipTab: { flex: 1, paddingVertical: 10, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EEF4FB', borderWidth: 1, borderColor: '#E8EEF6' },
    voipTabActive: { backgroundColor: '#0B2E5E', borderColor: '#0B2E5E' },
    voipTabText: { fontSize: 13, fontWeight: '800', color: '#5f6b80' },
    voipTabTextActive: { color: '#FFFFFF' },
    voipTabBadge: { position: 'absolute', top: 4, right: 8, minWidth: 18, height: 18, paddingHorizontal: 4, borderRadius: 9, backgroundColor: '#e5484d', alignItems: 'center', justifyContent: 'center' },
    voipTabBadgeText: { color: '#FFFFFF', fontSize: 10, fontWeight: '800' },
    bookingTileGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 12, marginTop: 4 },
    bookingTile: {
        width: '48%',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 18,
        paddingVertical: 20,
        paddingHorizontal: 12,
        borderWidth: 1,
        borderColor: '#E2F0E8',
        shadowColor: '#0B2E5E',
        shadowOpacity: 0.06,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        elevation: 2,
    },
    bookingTileIcon: { width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
    bookingTileEmoji: { fontSize: 26 },
    bookingTileLabel: { fontSize: 17, fontWeight: '900', color: '#1A1F36' },
    bookingTileSub: { fontSize: 12, color: '#6B7280', marginTop: 3 },
    bookingNearbyCard: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        backgroundColor: '#F1FBF6',
        borderRadius: 16,
        padding: 12,
        borderWidth: 1,
        borderColor: '#D6EEE1',
        marginTop: 12,
    },
    bookingNearbyThumb: {
        width: 64,
        height: 56,
        borderRadius: 12,
        backgroundColor: '#DDF3E8',
        alignItems: 'center',
        justifyContent: 'center',
    },
    bookingNearbyThumbEmoji: { fontSize: 26 },
    bookingNearbyBody: { flex: 1 },
    bookingNearbyTitle: { fontSize: 15, fontWeight: '900', color: '#1A1F36' },
    bookingNearbySub: { fontSize: 12, color: '#5f6b80', marginTop: 3, lineHeight: 17 },
    actionTile: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        paddingVertical: 14,
        paddingHorizontal: 16,
        borderWidth: 1,
        borderColor: '#E8EEF6',
        shadowColor: '#0B2E5E',
        shadowOpacity: 0.06,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        elevation: 2,
    },
    actionTileActive: { borderColor: '#1E6FE0', borderWidth: 2 },
    actionTileIcon: { width: 46, height: 46, borderRadius: 23, alignItems: 'center', justifyContent: 'center' },
    actionTileEmoji: { fontSize: 22 },
    actionTileTextWrap: { flex: 1 },
    actionTileLabel: { fontSize: 16, fontWeight: '800', color: '#1A1F36' },
    actionTileSub: { fontSize: 12, color: '#6B7280', marginTop: 2 },
    // ── 홈 런처 (mockup #1) ──
    homeGreetingWrap: { marginTop: 4, marginBottom: 14, paddingHorizontal: 4 },
    homeGreeting: { color: '#0b2e5e', fontSize: 24, fontWeight: '900' },
    homeGreetingSub: { color: '#5f6b80', fontSize: 14, marginTop: 4 },
    tourismPromoCard: {
        backgroundColor: '#ffffff',
        borderRadius: 18,
        borderWidth: 1.5,
        padding: 16,
        marginBottom: 14,
        overflow: 'hidden',
    },
    tourismPromoAccentBar: { position: 'absolute', left: 0, top: 0, bottom: 0, width: 4 },
    tourismPromoTitle: { color: '#1A1F36', fontSize: 18, fontWeight: '900', paddingLeft: 8 },
    tourismPromoSubtitle: { color: '#4a5f7f', fontSize: 13, fontWeight: '700', marginTop: 4, paddingLeft: 8 },
    tourismPromoBody: { color: '#5f6b80', fontSize: 13, lineHeight: 19, marginTop: 8, paddingLeft: 8 },
    tourismPromoMeta: { color: '#9aa7bd', fontSize: 11.5, marginTop: 6, paddingLeft: 8, fontWeight: '600' },
    tourismPromoCta: {
        alignSelf: 'flex-start',
        marginTop: 12,
        marginLeft: 8,
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 9,
    },
    tourismPromoCtaText: { color: '#ffffff', fontWeight: '800', fontSize: 13 },
    faceHeroCard: {
        backgroundColor: '#1E6FE0',
        borderRadius: 24,
        paddingVertical: 22,
        paddingHorizontal: 18,
        alignItems: 'center',
        marginBottom: 14,
        shadowColor: '#1E6FE0',
        shadowOpacity: 0.25,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 8 },
        elevation: 6,
    },
    faceHeroTitle: { color: '#ffffff', fontSize: 22, fontWeight: '900' },
    faceHeroSub: { color: '#cfe2ff', fontSize: 12, fontWeight: '600', marginTop: 2, marginBottom: 16 },
    faceHeroFlagRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 18, marginBottom: 18 },
    faceHeroLangCol: { alignItems: 'center', gap: 6, minWidth: 84 },
    faceHeroFlag: {
        fontSize: 30,
        width: 56,
        height: 56,
        lineHeight: 56,
        textAlign: 'center',
        borderRadius: 28,
        backgroundColor: 'rgba(255,255,255,0.18)',
        overflow: 'hidden',
    },
    faceHeroLangLabel: { color: '#ffffff', fontSize: 13, fontWeight: '700' },
    faceHeroSwap: { color: '#cfe2ff', fontSize: 22, fontWeight: '800' },
    faceHeroMic: {
        width: 84,
        height: 84,
        borderRadius: 42,
        backgroundColor: '#FF8A5B',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#FF8A5B',
        shadowOpacity: 0.5,
        shadowRadius: 14,
        shadowOffset: { width: 0, height: 6 },
        elevation: 8,
    },
    faceHeroMicActive: { backgroundColor: '#FF6A33', borderWidth: 4, borderColor: 'rgba(255,255,255,0.45)' },
    faceHeroMicIcon: { fontSize: 38 },
    faceHeroCta: { color: '#ffffff', fontSize: 15, fontWeight: '800', marginTop: 14 },
    homeQuickRow: { flexDirection: 'row', gap: 10, marginBottom: 14 },
    homeQuickBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 16,
        paddingVertical: 14,
        paddingHorizontal: 12,
    },
    homeQuickIcon: { fontSize: 22 },
    homeQuickTitle: { color: '#1a1f36', fontSize: 14, fontWeight: '800' },
    homeQuickSub: { color: '#5f6b80', fontSize: 11, marginTop: 2 },
    homeFavRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 16,
        paddingVertical: 14,
        paddingHorizontal: 14,
        marginBottom: 4,
    },
    homeFavIcon: { fontSize: 20 },
    homeFavTitle: { color: '#1a1f36', fontSize: 14, fontWeight: '800' },
    homeFavSub: { color: '#5f6b80', fontSize: 11, marginTop: 2 },
    homeFavChevron: { color: '#1e6fe0', fontSize: 18, fontWeight: '800' },
    // ── 대면통역 전용 화면 (mockup #2) ──
    faceScreenRoot: { flex: 1, backgroundColor: 'transparent' },
    faceScreenHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 14,
        paddingTop: 8,
        paddingBottom: 6,
        gap: 8,
    },
    faceScreenLogo: { color: '#1E6FE0', fontSize: 16, fontWeight: '900' },
    faceScreenLangPill: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.85)',
        borderWidth: 1,
        borderColor: '#bcd3f0',
        borderRadius: 999,
        paddingHorizontal: 14,
        paddingVertical: 7,
    },
    faceScreenLangPillText: { color: '#1a1f36', fontSize: 13, fontWeight: '700' },
    faceScreenClose: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(255,255,255,0.85)',
        borderWidth: 1,
        borderColor: '#bcd3f0',
        alignItems: 'center',
        justifyContent: 'center',
    },
    faceScreenCloseText: { color: '#1e6fe0', fontSize: 18, fontWeight: '800' },
    faceScreenBody: { flex: 1, position: 'relative' },
    facePeerHalf: {
        flex: 1,
        backgroundColor: 'rgba(227,240,255,0.72)',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 24,
        paddingBottom: 48,
    },
    faceRotated: { transform: [{ rotate: '180deg' }], alignItems: 'center', gap: 14 },
    facePeerLangLabel: { color: '#1e6fe0', fontSize: 14, fontWeight: '800' },
    facePeerText: { color: '#0b2e5e', fontSize: 12, fontWeight: '800', textAlign: 'center', lineHeight: 18 },
    faceMeHalf: {
        flex: 1,
        backgroundColor: 'rgba(255,255,255,0.88)',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 24,
        paddingTop: 48,
        gap: 14,
    },
    faceTapHint: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#eef4fb',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 999,
        paddingHorizontal: 14,
        paddingVertical: 7,
    },
    faceTapHintText: { color: '#5f6b80', fontSize: 13, fontWeight: '700' },
    faceMeText: { color: '#0b2e5e', fontSize: 12, fontWeight: '800', textAlign: 'center', lineHeight: 18 },
    faceMeLangLabel: { color: '#1e6fe0', fontSize: 14, fontWeight: '800' },
    faceMicWrap: {
        position: 'absolute',
        top: '50%',
        left: 0,
        right: 0,
        alignItems: 'center',
        transform: [{ translateY: -14 }],
        zIndex: 10,
    },
    faceMicWaveShell: {
        minWidth: 252,
        minHeight: 52,
        borderRadius: 14,
        backgroundColor: 'rgba(255,255,255,0.94)',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'rgba(30,111,224,0.12)',
        paddingHorizontal: 14,
        paddingVertical: 8,
        gap: 4,
        shadowColor: '#0B2E5E',
        shadowOpacity: 0.06,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 3 },
        elevation: 3,
    },
    faceMicWaveAura: {
        position: 'absolute',
        width: 0,
        height: 0,
        borderRadius: 0,
        backgroundColor: 'transparent',
    },
    faceMicWaveAuraActive: {
        backgroundColor: 'transparent',
    },
    faceMicWaveAuraSpeech: {
        backgroundColor: 'transparent',
    },
    faceMicWaveRail: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        minHeight: 18,
        width: '100%',
    },
    faceMicWaveBar: {
        width: 4,
        minHeight: 3,
        borderRadius: 3,
        backgroundColor: '#9AB8E6',
    },
    faceMicWaveBarListening: {
        backgroundColor: '#4E8EEA',
    },
    faceMicWaveBarSpeech: {
        backgroundColor: '#0DB48B',
    },
    faceMicWaveLabel: {
        color: '#6B7A90',
        fontSize: 10,
        fontWeight: '700',
        letterSpacing: 0.2,
    },
    faceMicWaveLabelListening: {
        color: '#1E6FE0',
    },
    faceMicWaveLabelSpeech: {
        color: '#0E8F6E',
        fontWeight: '800',
    },
    faceMicWaveLabelProcessing: {
        color: '#8A4DFF',
        fontWeight: '800',
    },
    faceTabBar: {
        flexDirection: 'row',
        backgroundColor: 'rgba(255,255,255,0.92)',
        borderTopWidth: 1,
        borderTopColor: '#dce6f2',
        paddingVertical: 8,
    },
    faceTabItem: { flex: 1, alignItems: 'center', gap: 2 },
    faceTabIcon: { fontSize: 20 },
    faceTabLabel: { color: '#8a93a3', fontSize: 11, fontWeight: '700' },
    faceTabLabelActive: { color: '#1e6fe0', fontSize: 11, fontWeight: '800' },
    lobbyShell: { gap: 14, marginBottom: 18 },
    lobbyHeroCard: {
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 18,
        padding: 16,
        gap: 8,
    },
    lobbyHeroEyebrow: { color: '#1e6fe0', fontSize: 12, fontWeight: '800', textTransform: 'uppercase' },
    lobbyHeroTitle: { color: '#0b2e5e', fontSize: 21, fontWeight: '900', lineHeight: 29 },
    lobbyHeroBody: { color: '#5a6b8c', fontSize: 13, lineHeight: 20 },
    lobbyPreviewGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
    lobbyPreviewCard: {
        width: '48%',
        minHeight: 108,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 14,
        padding: 10,
        gap: 4,
    },
    lobbyPreviewIcon: { fontSize: 18 },
    lobbyPreviewTitle: { color: '#0b2e5e', fontSize: 13, fontWeight: '800' },
    lobbyPreviewBody: { color: '#5a6b8c', fontSize: 11, lineHeight: 16 },
    workspaceShell: { marginBottom: 12 },
    workspaceHeaderCard: {
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 12,
        padding: 8,
        gap: 6,
    },
    workspaceHeaderTitle: { color: '#0b2e5e', fontSize: 11, fontWeight: '900' },
    workspaceHeaderBody: { color: '#5a6b8c', fontSize: 8, lineHeight: 11 },
    workspaceRailGrid: { flexDirection: 'row', flexWrap: 'nowrap', gap: 4, justifyContent: 'space-between' },
    workspaceRailCard: {
        width: '19%',
        minHeight: 38,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 10,
        paddingHorizontal: 4,
        paddingVertical: 5,
        gap: 2,
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    workspaceRailCardActive: { backgroundColor: '#e3f0ff', borderColor: '#1e6fe0' },
    workspaceRailIcon: { fontSize: 8 },
    workspaceRailTitle: { color: '#0b2e5e', fontSize: 7, fontWeight: '800', textAlign: 'center' },
    workspaceRailMeta: { color: '#5a6b8c', fontSize: 6, lineHeight: 7, textAlign: 'center' },
    translationHub: { position: 'relative', marginBottom: 14 },
    header: { alignItems: 'center', marginBottom: 14, paddingTop: 6 },
    title: { fontSize: 24, fontWeight: '800', color: '#0b2e5e', letterSpacing: 0.3 },
    subtitle: { fontSize: 12, color: '#5a6b8c', marginTop: 2 },
    travelModeBanner: {
        marginBottom: 16,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 18,
        padding: 14,
        gap: 10,
    },
    travelModeTitle: { color: '#0b2e5e', fontSize: 16, fontWeight: '800' },
    travelModeBody: { color: '#5a6b8c', fontSize: 13, lineHeight: 19 },
    travelModeActionRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
    versionPillRow: { marginTop: 10, flexDirection: 'row', gap: 8, alignItems: 'center', flexWrap: 'wrap', justifyContent: 'center' },
    versionPill: {
        backgroundColor: '#e8f1ff',
        borderWidth: 1,
        borderColor: '#bcd3f0',
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 7,
    },
    versionPillText: { color: '#1e6fe0', fontSize: 12, fontWeight: '800' },
    voipLaunchBtn: {
        backgroundColor: '#e6f7ef',
        borderWidth: 1,
        borderColor: '#9be8b3',
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    voipLaunchBtnText: { color: '#0f7a4d', fontSize: 11, fontWeight: '800' },
    badge: {
        marginTop: 8,
        backgroundColor: C.badge,
        paddingHorizontal: 10,
        paddingVertical: 3,
        borderRadius: 12,
    },
    badgeText: { fontSize: 12, color: C.sub },
    accountRow: {
        marginTop: 10,
        flexDirection: 'row',
        gap: 8,
    },
    inlineAuthPanel: {
        marginTop: 12,
        width: '100%',
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 14,
        padding: 12,
    },
    inlineAuthHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 8,
        marginBottom: 6,
    },
    inlineAuthTitle: { color: '#0b2e5e', fontSize: 15, fontWeight: '800' },
    inlineAuthHint: { color: C.sub, fontSize: 12, lineHeight: 18, marginBottom: 10 },
    inlineAuthModeChip: {
        backgroundColor: '#e8f1ff',
        borderWidth: 1,
        borderColor: '#bcd3f0',
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    inlineAuthModeChipText: { color: '#1e6fe0', fontSize: 11, fontWeight: '700' },
    inlineAuthStatus: {
        color: '#1e6fe0',
        fontSize: 12,
        lineHeight: 18,
        marginBottom: 8,
    },
    authDebugPanel: {
        width: '100%',
        marginTop: 10,
        padding: 10,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#5c4b18',
        backgroundColor: '#1f1a0c',
        gap: 3,
    },
    authDebugTitle: {
        color: '#ffd76b',
        fontSize: 11,
        fontWeight: '800',
    },
    authDebugLine: {
        color: '#f7e7b1',
        fontSize: 11,
        lineHeight: 16,
    },
    authDebugFloating: {
        position: 'absolute',
        top: 18,
        right: 16,
        width: 280,
        padding: 10,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#5c4b18',
        backgroundColor: 'rgba(31, 26, 12, 0.92)',
        zIndex: 30,
    },
    authDebugActionBtn: {
        marginTop: 8,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#9a7a1a',
        backgroundColor: '#35270a',
        paddingHorizontal: 10,
        paddingVertical: 9,
        alignItems: 'center',
    },
    authDebugActionBtnText: {
        color: '#ffe08c',
        fontSize: 12,
        fontWeight: '800',
    },
    inlineAuthActionRow: {
        flexDirection: 'row',
        gap: 8,
        flexWrap: 'wrap',
        alignItems: 'center',
    },
    inlineAuthUtilityRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 10,
        marginTop: 2,
    },
    authUtilityLinkText: {
        color: '#1e6fe0',
        fontSize: 12,
        fontWeight: '700',
    },
    myInfoActionRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginTop: 8,
    },
    inlineAuthSubmitBtn: {
        flex: 1,
        minWidth: 120,
    },
    sectionRailDock: {
        position: 'absolute',
        left: 16,
        right: 16,
        bottom: 14,
        alignItems: 'center',
        gap: 8,
    },
    sectionRail: {
        backgroundColor: 'rgba(232, 241, 255, 0.96)',
        position: 'relative',
        borderWidth: 1,
        borderColor: '#bcd3f0',
        borderRadius: 18,
        paddingVertical: 8,
        paddingHorizontal: 10,
        gap: 10,
    },
    sectionRailBadge: {
        position: 'absolute',
        top: 6,
        right: 6,
        borderRadius: 999,
        backgroundColor: '#c2410c',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderWidth: 1,
        borderColor: '#fdba74',
        zIndex: 2,
    },
    sectionRailBadgeText: { color: '#fff7ed', fontSize: 9, fontWeight: '900' },
    sectionRailToggleBtn: {
        minWidth: 118,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        backgroundColor: 'rgba(255, 255, 255, 0.96)',
        borderWidth: 1,
        borderColor: '#bcd3f0',
        borderRadius: 999,
        paddingHorizontal: 14,
        paddingVertical: 9,
    },
    sectionRailToggleBtnActive: { borderColor: '#1e6fe0', backgroundColor: '#e3f0ff' },
    sectionRailToggleIcon: { color: '#1e6fe0', fontSize: 13, fontWeight: '800' },
    sectionRailToggleText: { color: '#1a1f36', fontSize: 12, fontWeight: '800' },
    sectionRailBtn: {
        width: 54,
        minHeight: 50,
        borderRadius: 12,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 6,
        gap: 3,
    },
    sectionRailBtnActive: { backgroundColor: '#e3f0ff', borderColor: '#1e6fe0' },
    sectionRailIcon: { fontSize: 15 },
    sectionRailLabel: { color: '#1a1f36', fontSize: 9, fontWeight: '700' },
    sectionCardActive: { borderColor: '#1e6fe0', shadowColor: '#1e6fe0', shadowOpacity: 0.18, shadowRadius: 12 },
    railOverlayScrim: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(5, 10, 18, 0.44)',
        borderRadius: 22,
        paddingHorizontal: 14,
        paddingTop: 92,
        paddingBottom: 18,
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    railOverlayCard: {
        width: '92%',
        minHeight: 248,
        backgroundColor: 'rgba(255, 255, 255, 0.98)',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 20,
        paddingHorizontal: 16,
        paddingVertical: 16,
        gap: 10,
        shadowColor: '#000',
        shadowOpacity: 0.24,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: 10 },
    },
    railOverlayHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
    railOverlayTitle: { color: '#0b2e5e', fontSize: 18, fontWeight: '800', flex: 1 },
    railOverlayCloseBtn: {
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: '#e8f1ff',
        borderWidth: 1,
        borderColor: '#bcd3f0',
        alignItems: 'center',
        justifyContent: 'center',
    },
    railOverlayCloseText: { color: '#1e6fe0', fontSize: 22, fontWeight: '800' },
    railOverlayBodyText: { color: '#3a4356', fontSize: 14, lineHeight: 22 },
    railOverlayActionRow: { flexDirection: 'row', gap: 10, flexWrap: 'wrap', marginTop: 4 },
    railOverlayActionBtn: {
        backgroundColor: '#1e6fe0',
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 10,
        minHeight: 44,
        alignItems: 'center',
        justifyContent: 'center',
    },
    railOverlayActionText: { color: '#f7fbff', fontSize: 13, fontWeight: '800' },
    railOverlayGhostBtn: {
        backgroundColor: '#e8f1ff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#bcd3f0',
        paddingHorizontal: 14,
        paddingVertical: 10,
        minHeight: 44,
        alignItems: 'center',
        justifyContent: 'center',
    },
    railOverlayGhostText: { color: '#1e6fe0', fontSize: 13, fontWeight: '700' },
    socialHubRow: { flexDirection: 'row', gap: 12, marginTop: 8 },
    interCallQuickRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap', marginTop: 8 },
    interCallHint: { color: '#5f6b80', fontSize: 12, lineHeight: 18, marginTop: 6 },
    socialHubBtn: {
        flex: 1,
        minHeight: 112,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#dce6f2',
        backgroundColor: '#ffffff',
        paddingHorizontal: 10,
        paddingVertical: 10,
        gap: 4,
    },
    socialHubBtnActive: { borderColor: '#1e6fe0', backgroundColor: '#e3f0ff' },
    socialHubIcon: { fontSize: 19 },
    socialHubTitle: { color: '#1a1f36', fontSize: 14, fontWeight: '800' },
    socialHubMeta: { color: '#5f6b80', fontSize: 11, lineHeight: 16 },
    loginBtn: {
        backgroundColor: '#e8f1ff',
        borderWidth: 1,
        borderColor: '#1e6fe0',
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 8,
    },
    loginBtnText: { color: '#1e6fe0', fontWeight: '700', fontSize: 13 },
    myInfoBtn: {
        backgroundColor: '#e6f7ef',
        borderWidth: 1,
        borderColor: '#19c37d',
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 8,
    },
    myInfoBtnText: { color: '#1f9d57', fontWeight: '700', fontSize: 12 },
    logoutBtn: {
        backgroundColor: C.surface,
        borderWidth: 1,
        borderColor: C.border,
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 8,
    },
    logoutBtnText: { color: C.sub, fontWeight: '700', fontSize: 12 },
    myInfoPanel: {
        marginTop: 10,
        width: '100%',
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: C.border,
        borderRadius: 10,
        padding: 10,
    },
    myInfoTitle: { color: '#0b2e5e', fontWeight: '800', marginBottom: 6 },
    myInfoText: { color: C.sub, fontSize: 12, marginBottom: 4 },
    purchaseListWrap: {
        marginTop: 8,
        backgroundColor: '#f4f9ff',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: C.border,
        padding: 8,
        gap: 4,
    },
    purchaseItemText: { color: C.sub, fontSize: 12 },
    labelRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 12 },
    label: { fontSize: 12, color: C.sub, marginBottom: 8 },
    gpsStatusText: { color: '#1e6fe0', fontSize: 12, marginTop: 2, marginBottom: 8 },
    gpsBtn: {
        backgroundColor: '#e8f1ff',
        borderWidth: 1,
        borderColor: '#bcd3f0',
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    gpsBtnText: { color: '#1e6fe0', fontSize: 12, fontWeight: '700' },
    gpsAutoBadge: { color: '#1e6fe0', fontSize: 11, fontWeight: '700' },
    langAutoChip: {
        backgroundColor: C.surface,
        borderWidth: 1,
        borderColor: C.border,
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 9,
        marginBottom: 4,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    langAutoChipValue: { color: C.text, fontSize: 13, fontWeight: '700' },
    langAutoChipHint: { color: '#0f7a4d', fontSize: 11, fontWeight: '700' },
    autoVoiceModeStatus: { color: C.sub, fontSize: 12, lineHeight: 18 },
    socialHubBtnPassive: {
        flex: 1,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 12,
        padding: 12,
        minHeight: 92,
    },
    langPickerValue: { color: C.text, fontSize: 13, fontWeight: '700' },
    langPickerHint: { color: C.sub, fontSize: 11 },
    langModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        justifyContent: 'center',
        paddingHorizontal: 20,
    },
    langModalCard: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: C.border,
        padding: 12,
        maxHeight: '78%',
    },
    langModalTitle: { color: '#0b2e5e', fontSize: 16, fontWeight: '800', marginBottom: 10 },
    langModalList: { maxHeight: 300, marginTop: 8 },
    langModalListBody: { gap: 8, paddingBottom: 12 },
    langModalOption: {
        paddingVertical: 11,
        paddingHorizontal: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: C.border,
        marginBottom: 8,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#f4f9ff',
    },
    langModalOptionActive: {
        borderColor: C.accent,
        backgroundColor: '#e3f0ff',
    },
    langModalOptionText: { color: C.text, fontSize: 14 },
    langModalOptionTextActive: { color: '#1e6fe0', fontWeight: '800' },
    langModalCheck: { color: '#1e6fe0', fontWeight: '800', fontSize: 16 },
    langModalCloseBtn: {
        alignSelf: 'flex-end',
        marginTop: 6,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        backgroundColor: C.surface,
        borderWidth: 1,
        borderColor: C.border,
    },
    langModalCloseText: { color: C.sub, fontWeight: '700' },
    inputBox: {
        backgroundColor: C.surface,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: C.border,
        padding: 10,
        marginTop: 6,
        minHeight: 96,
    },
    resultBox: { minHeight: 96 },
    resultActionRow: { marginTop: 8, flexDirection: 'row', justifyContent: 'flex-end' },
    ocrCard: {
        marginTop: 12,
        backgroundColor: '#ffffff',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: C.border,
        padding: 12,
        gap: 8,
    },
    ocrTitle: { color: '#0b2e5e', fontSize: 15, fontWeight: '800' },
    ocrSubtitle: { color: C.sub, fontSize: 12, lineHeight: 18 },
    ocrPreviewBox: {
        marginTop: 4,
        backgroundColor: '#f4f9ff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 8,
        padding: 10,
        gap: 6,
    },
    textInput: { flex: 1, color: C.text, fontSize: 14, minHeight: 68, textAlignVertical: 'top' },
    settingsGearButton: {
        position: 'absolute',
        top: 10,
        right: 10,
        zIndex: 50,
        width: 38,
        height: 38,
        borderRadius: 19,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255,255,255,0.92)',
        borderWidth: 1,
        borderColor: '#dce6f2',
    },
    settingsGearIcon: { fontSize: 18 },
    settingsOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.6)',
        justifyContent: 'flex-end',
    },
    settingsCard: {
        backgroundColor: '#ffffff',
        borderTopLeftRadius: 18,
        borderTopRightRadius: 18,
        borderWidth: 1,
        borderColor: '#dce6f2',
        paddingHorizontal: 16,
        paddingTop: 14,
        paddingBottom: 18,
        maxHeight: '88%',
    },
    settingsHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    settingsTitle: { color: '#0b2e5e', fontSize: 17, fontWeight: '900' },
    settingsCloseText: { color: C.sub, fontSize: 18, fontWeight: '800', paddingHorizontal: 6 },
    settingsScroll: { maxHeight: 520 },
    settingsSectionTitle: { color: '#0b2e5e', fontSize: 14, fontWeight: '800', marginBottom: 2 },
    settingsSectionSub: { color: C.sub, fontSize: 12, lineHeight: 17, marginBottom: 8 },
    settingsSegmentRow: { flexDirection: 'row', gap: 8 },
    settingsSegment: {
        flex: 1,
        paddingVertical: 11,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: C.border,
        backgroundColor: C.surface,
        alignItems: 'center',
    },
    settingsSegmentActive: { backgroundColor: '#1f6feb', borderColor: '#1f6feb' },
    settingsSegmentText: { color: C.text, fontSize: 13, fontWeight: '700' },
    settingsSegmentTextActive: { color: '#ffffff', fontWeight: '900' },
    settingsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: C.border,
        backgroundColor: C.surface,
        marginTop: 8,
    },
    settingsRowLabel: { color: C.sub, fontSize: 13, fontWeight: '700' },
    settingsRowValue: { color: '#0b2e5e', fontSize: 13, fontWeight: '800', flexShrink: 1, textAlign: 'right', marginLeft: 12 },
    settingsPickerList: {
        maxHeight: 220,
        marginTop: 6,
        borderWidth: 1,
        borderColor: C.border,
        borderRadius: 10,
        backgroundColor: '#f4f9ff',
    },
    settingsActionBtn: {
        marginTop: 8,
        paddingVertical: 12,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#bcd3f0',
        backgroundColor: '#e8f1ff',
        alignItems: 'center',
    },
    settingsActionBtnText: { color: '#1e6fe0', fontSize: 14, fontWeight: '800' },
    settingsDoneBtn: {
        marginTop: 14,
        paddingVertical: 13,
        borderRadius: 12,
        backgroundColor: '#1f6feb',
        alignItems: 'center',
    },
    settingsDoneBtnText: { color: '#ffffff', fontSize: 15, fontWeight: '900' },
    resultText: { color: C.text, fontSize: 14 },
    resultPlaceholder: { color: C.sub, fontSize: 14 },
    speakBtn: { alignSelf: 'flex-end', marginTop: 6 },
    speakIcon: { fontSize: 20 },
    inputBtnRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 6 },
    voiceMicBtn: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, backgroundColor: C.badge },
    voiceMicBtnActive: { backgroundColor: '#7c1d1d' },
    actionRow: { flexDirection: 'row', gap: 8, marginTop: 10 },
    swapBtn: {
        flex: 1,
        backgroundColor: C.surface,
        borderWidth: 1,
        borderColor: C.border,
        borderRadius: 10,
        paddingVertical: 10,
        alignItems: 'center',
    },
    swapText: { color: C.sub, fontSize: 12, fontWeight: '600' },
    translateBtn: {
        flex: 2,
        backgroundColor: C.green,
        borderRadius: 10,
        paddingVertical: 10,
        alignItems: 'center',
    },
    translateBtnDisabled: { opacity: 0.6 },
    translateBtnText: { color: '#fff', fontSize: 14, fontWeight: '800' },
    offlineBanner: {
        backgroundColor: '#2a1a00',
        borderRadius: 8,
        padding: 10,
        marginTop: 10,
        borderWidth: 1,
        borderColor: '#5a3a00',
    },
    offlineText: { color: '#f0b050', fontSize: 12 },
    sectionCard: {
        marginTop: 12,
        backgroundColor: C.surface,
        borderWidth: 1,
        borderColor: C.border,
        borderRadius: 10,
        padding: 10,
    },
    voipRailWorkspaceCard: {
        marginTop: 10,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 12,
        padding: 10,
        gap: 6,
    },
    voipIncomingBanner: {
        marginTop: 14,
        backgroundColor: '#e8f1ff',
        borderWidth: 1,
        borderColor: '#bcd3f0',
        borderRadius: 14,
        padding: 14,
        gap: 8,
    },
    voipActiveCallBanner: {
        marginTop: 14,
        backgroundColor: '#e6f7ef',
        borderWidth: 1,
        borderColor: '#19c37d',
        borderRadius: 14,
        padding: 14,
        gap: 8,
    },
    voipIncomingBannerHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 10,
        flexWrap: 'wrap',
    },
    voipIncomingBannerTitle: { color: '#0b2e5e', fontSize: 16, fontWeight: '900' },
    voipIncomingBannerBody: { color: '#3a4356', fontSize: 12, lineHeight: 18 },
    voipIncomingBannerMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    voipIncomingBannerMeta: { color: '#5f6b80', fontSize: 11, fontWeight: '700' },
    voipIncomingFixedPanel: {
        position: 'absolute',
        top: 70,
        left: 14,
        right: 14,
        zIndex: 80,
        elevation: 20,
    },
    voipIncomingFixedCard: {
        backgroundColor: '#ffffff',
        borderWidth: 2,
        borderColor: '#1e6fe0',
        borderRadius: 12,
        padding: 14,
        gap: 8,
        shadowColor: '#1a2540',
        shadowOpacity: 0.18,
        shadowRadius: 14,
        shadowOffset: { width: 0, height: 6 },
    },
    voipIncomingFixedTitle: { color: '#0b2e5e', fontSize: 18, fontWeight: '900' },
    voipIncomingFixedCaller: { color: '#3a4356', fontSize: 14, fontWeight: '700', lineHeight: 20 },
    voipIncomingFixedActions: { flexDirection: 'row', gap: 10 },
    voipIncomingAcceptBtn: {
        flex: 1,
        backgroundColor: '#19a463',
        borderRadius: 10,
        paddingVertical: 13,
        alignItems: 'center',
    },
    voipIncomingRejectBtn: {
        flex: 1,
        backgroundColor: '#e5484d',
        borderRadius: 10,
        paddingVertical: 13,
        alignItems: 'center',
    },
    voipIncomingAcceptBtnText: { color: '#ffffff', fontSize: 16, fontWeight: '900' },
    voipIncomingRejectBtnText: { color: '#ffffff', fontSize: 16, fontWeight: '900' },
    voipIncomingConnectingRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 4 },
    voipIncomingConnectingText: { color: '#1E6FE0', fontSize: 13, fontWeight: '700', flex: 1 },
    voipIncomingActionDisabled: { opacity: 0.55 },
    voipIncomingRailCard: {
        marginTop: 12,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 14,
        padding: 14,
        gap: 8,
    },
    sectionTitle: { color: '#1a1f36', fontSize: 15, fontWeight: '800' },
    sectionSub: { color: C.sub, fontSize: 11, marginTop: 3, marginBottom: 8, lineHeight: 16 },
    voipQuickMetaRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap', marginBottom: 8 },
    voipQuickMetaText: { color: '#1f9d57', fontSize: 12, fontWeight: '700' },
    voipLocalLangCard: {
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#dce6f2',
        backgroundColor: '#ffffff',
        padding: 12,
        marginBottom: 10,
        gap: 6,
    },
    voipLocalLangTitle: { color: '#1a1f36', fontSize: 14, fontWeight: '800' },
    voipLocalLangSub: { color: '#5f6b80', fontSize: 11, lineHeight: 16 },
    voipLocalLangTrigger: {
        minHeight: 54,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#dce6f2',
        backgroundColor: '#f4f9ff',
        paddingHorizontal: 14,
        paddingVertical: 10,
        marginTop: 4,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    voipLocalLangValue: { color: '#1a1f36', fontSize: 15, fontWeight: '800' },
    voipLocalLangMeta: { color: '#5f6b80', fontSize: 11, marginTop: 4 },
    voipLocalLangHint: { color: '#1e6fe0', fontSize: 13, fontWeight: '800' },
    voipLocalLangResetBtn: { alignSelf: 'flex-start', paddingVertical: 4 },
    voipLocalLangResetText: { color: '#e07b39', fontSize: 12, fontWeight: '700' },
    premiumHubRow: { gap: 10 },
    monetizationCard: {
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 14,
        padding: 14,
        gap: 8,
        marginBottom: 10,
    },
    monetizationCardPrimary: {
        borderColor: '#1e6fe0',
        backgroundColor: '#eef4fb',
    },
    connectionStateCard: {
        borderColor: '#dce6f2',
        backgroundColor: '#f4f9ff',
    },
    connectionStateTitle: {
        color: '#1a1f36',
        fontSize: 16,
        fontWeight: '800',
    },
    connectionStateBody: {
        color: '#3a4356',
        fontSize: 13,
        lineHeight: 20,
    },
    connectionStateHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 8,
    },
    connectionStateBadge: {
        color: '#b3791f',
        backgroundColor: '#fdf3e0',
        borderWidth: 1,
        borderColor: '#f0d9a8',
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 5,
        overflow: 'hidden',
        fontSize: 11,
        fontWeight: '800',
    },
    connectionStateBadgeReady: {
        color: '#1f9d57',
        backgroundColor: '#e6f7ef',
        borderColor: '#b6e4c4',
    },
    connectionStateBulletList: {
        gap: 4,
    },
    connectionStateBullet: {
        color: '#3a4356',
        fontSize: 12,
        lineHeight: 18,
    },
    connectionStateActionRow: {
        flexDirection: 'row',
        gap: 8,
        flexWrap: 'wrap',
        alignItems: 'center',
    },
    monetizationBadge: {
        alignSelf: 'flex-start',
        backgroundColor: '#e3f0ff',
        color: '#1e6fe0',
        fontSize: 11,
        fontWeight: '800',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 999,
        overflow: 'hidden',
    },
    monetizationTitle: { color: '#1a1f36', fontSize: 18, fontWeight: '800' },
    monetizationBody: { color: '#3a4356', fontSize: 13, lineHeight: 20 },
    monetizationMetricRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
    monetizationMetric: {
        color: '#1f9d57',
        fontSize: 12,
        fontWeight: '700',
    },
    planGrid: { gap: 10 },
    planCard: {
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 12,
        padding: 12,
        gap: 6,
    },
    planCardOwned: {
        borderColor: '#14b8a6',
        backgroundColor: '#e6f7f4',
    },
    planTitle: { color: '#1a1f36', fontSize: 15, fontWeight: '800' },
    planPrice: { color: '#1f9d57', fontSize: 14, fontWeight: '800' },
    planUsage: { color: '#3a4356', fontSize: 12, lineHeight: 18 },
    planFormula: { color: '#5f6b80', fontSize: 11, lineHeight: 17 },
    premiumStatusText: {
        color: '#1e6fe0',
        fontSize: 12,
        lineHeight: 18,
        marginBottom: 8,
    },
    songPayCard: {
        borderColor: '#c4e3b0',
        backgroundColor: '#f1f8ec',
    },
    songModeActionRow: { flexDirection: 'row', gap: 8, alignItems: 'center', marginBottom: 8, flexWrap: 'wrap' },
    inlineGhostBtn: {
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 10,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: C.border,
    },
    inlineGhostBtnDisabled: { opacity: 0.55 },
    inlineGhostBtnText: { color: C.sub, fontWeight: '700', fontSize: 12 },
    songModeMetaText: { color: C.sub, fontSize: 12, lineHeight: 18, marginBottom: 4 },
    songModeStatusText: {
        marginTop: 4,
        marginBottom: 8,
        color: '#1e6fe0',
        fontSize: 12,
        lineHeight: 18,
    },
    songSubtitleWrap: {
        marginTop: 6,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: C.border,
        borderRadius: 10,
        padding: 10,
        gap: 8,
    },
    songSubtitlePlaceholder: { color: C.sub, fontSize: 12, lineHeight: 18 },
    songSubtitleItem: {
        backgroundColor: '#f4f9ff',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#dce6f2',
        padding: 10,
        gap: 4,
    },
    songSubtitleOriginal: { color: '#1a1f36', fontSize: 14, fontWeight: '700' },
    songSubtitleTranslated: { color: '#1f9d57', fontSize: 14, lineHeight: 20 },
    songSubtitleMeta: { color: '#1e6fe0', fontSize: 11 },
    songFileJobBox: {
        marginTop: 8,
        marginBottom: 8,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 10,
        padding: 10,
        gap: 8,
    },
    songFileJobHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
    songFileNameText: { color: '#1a1f36', fontSize: 13, fontWeight: '800', flex: 1 },
    songFileProgressText: { color: '#1f9d57', fontSize: 12, fontWeight: '800' },
    songFileProgressTrack: { height: 6, borderRadius: 999, backgroundColor: '#e3eaf5', overflow: 'hidden' },
    songFileProgressFill: { height: 6, borderRadius: 999, backgroundColor: '#14b8a6' },
    songFileControlRow: { flexDirection: 'row', alignItems: 'center', gap: 10, flexWrap: 'wrap' },
    voicePreviewPanel: {
        marginTop: 8,
        marginBottom: 8,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#bcd3f0',
        borderRadius: 10,
        padding: 10,
        gap: 8,
    },
    voicePreviewHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
    voiceAckRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: '#f4f9ff',
        borderWidth: 1,
        borderColor: C.border,
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 9,
    },
    voiceAckMark: {
        width: 20,
        height: 20,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: '#1e6fe0',
        color: '#1f9d57',
        textAlign: 'center',
        lineHeight: 18,
        fontWeight: '800',
    },
    voiceAckText: { color: C.sub, fontSize: 12, lineHeight: 17, flex: 1 },
    voicePreviewResultBox: {
        backgroundColor: '#f4f9ff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 8,
        padding: 8,
        gap: 6,
    },
    songFileTimelineWrap: {
        marginTop: 8,
        marginBottom: 8,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: C.border,
        borderRadius: 10,
        padding: 10,
        gap: 8,
    },
    songFileTimelineTitle: { color: '#1a1f36', fontSize: 14, fontWeight: '800' },
    songFileExportRow: { flexDirection: 'row', gap: 6, flexWrap: 'wrap' },
    songFileExportBtn: {
        paddingHorizontal: 10,
        paddingVertical: 7,
        borderRadius: 8,
        backgroundColor: '#e8f1ff',
        borderWidth: 1,
        borderColor: '#dce6f2',
    },
    songFileExportText: { color: '#1f9d57', fontSize: 11, fontWeight: '800' },
    songFileSegmentItem: {
        backgroundColor: '#f4f9ff',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#dce6f2',
        padding: 10,
        gap: 6,
    },
    songFileSegmentItemActive: { borderColor: '#19c37d', backgroundColor: '#e6f7ef' },
    songFileSegmentInput: {
        minHeight: 52,
        backgroundColor: '#f4f9ff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        color: '#1a7a4a',
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 8,
        fontSize: 14,
        lineHeight: 20,
        textAlignVertical: 'top',
    },
    songFileSegmentFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
    songFileSaveBtn: {
        paddingHorizontal: 10,
        paddingVertical: 7,
        borderRadius: 8,
        backgroundColor: '#e6f7ef',
        borderWidth: 1,
        borderColor: '#19c37d',
    },
    songFileSaveText: { color: '#1f9d57', fontSize: 11, fontWeight: '800' },
    songFileExportPreview: {
        color: C.sub,
        fontSize: 11,
        lineHeight: 16,
        backgroundColor: '#f4f9ff',
        borderRadius: 8,
        padding: 10,
    },
    coordRow: { flexDirection: 'row', gap: 10 },
    coordField: { flex: 1 },
    coordLabel: { color: C.sub, fontSize: 11, marginBottom: 5 },
    compactInput: {
        backgroundColor: '#f4f9ff',
        borderWidth: 1,
        borderColor: C.border,
        color: C.text,
        borderRadius: 10,
        paddingHorizontal: 9,
        paddingVertical: 7,
        marginBottom: 8,
        fontSize: 12,
    },
    noteInput: { minHeight: 64, textAlignVertical: 'top' },
    railRow: { gap: 8, paddingRight: 8, marginBottom: 8 },
    railBtn: {
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: C.border,
    },
    railBtnActive: { backgroundColor: '#1e6fe0', borderColor: '#1e6fe0' },
    railBtnText: { color: C.sub, fontSize: 13, fontWeight: '600' },
    railBtnTextActive: { color: '#fff' },
    bookingSelectionBanner: {
        marginTop: 8,
        backgroundColor: '#e6f7ef',
        borderWidth: 1,
        borderColor: '#b6e4c4',
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 8,
        gap: 4,
    },
    bookingSelectionBannerTitle: { color: '#1f9d57', fontSize: 11, fontWeight: '800' },
    bookingSelectionBannerPlace: { color: '#1a1f36', fontSize: 13, fontWeight: '800' },
    bookingSelectionBannerMeta: { color: '#3a4356', fontSize: 11, lineHeight: 15 },
    bookingSelectionBannerStatic: { color: '#1f9d57', fontSize: 12, fontWeight: '800', marginTop: 2 },
    bookingSelectionBannerNotice: { color: '#1e6fe0', fontSize: 12, fontWeight: '700' },
    nearbyMapWrap: {
        marginTop: 8,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: C.border,
        borderRadius: 10,
        overflow: 'hidden',
    },
    nearbyMapHeaderRow: {
        paddingHorizontal: 12,
        paddingTop: 10,
        paddingBottom: 8,
        gap: 3,
        backgroundColor: '#f4f9ff',
        borderBottomWidth: 1,
        borderBottomColor: C.border,
    },
    nearbyMapTitle: { color: '#1a1f36', fontWeight: '800', fontSize: 13 },
    nearbyMapSubtitle: { color: '#1e6fe0', fontSize: 12 },
    nearbyMapWebView: {
        height: 140,
        backgroundColor: '#eef4fb',
    },
    nearbyListWrap: { marginTop: 6, gap: 8 },
    placeItem: {
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: C.border,
        borderRadius: 10,
        padding: 8,
    },
    placeItemActive: { borderColor: '#1e6fe0', backgroundColor: '#e3f0ff' },
    placeName: { color: '#1a1f36', fontWeight: '800', fontSize: 13 },
    placeMeta: { color: '#1e6fe0', fontSize: 11, marginTop: 3 },
    placeAddr: { color: C.sub, fontSize: 11, marginTop: 3, lineHeight: 15 },
    placeActionRow: { flexDirection: 'row', gap: 6, marginTop: 6 },
    inlineActionBtn: {
        backgroundColor: '#e8f1ff',
        borderWidth: 1,
        borderColor: '#bcd3f0',
        borderRadius: 8,
        paddingHorizontal: 8,
        paddingVertical: 6,
    },
    inlineActionBtnActive: { backgroundColor: '#e6f7ef', borderColor: '#19c37d' },
    inlineActionBtnText: { color: '#1e6fe0', fontSize: 11, fontWeight: '700' },
    inlineActionBtnTextActive: { color: '#1f9d57' },
    autoVoiceModeWrap: { marginBottom: 10, gap: 6 },
    hotelRailBtn: {
        width: 170,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: C.border,
        borderRadius: 10,
        padding: 10,
    },
    hotelRailBtnActive: { borderColor: '#19c37d', backgroundColor: '#e6f7ef' },
    hotelRailName: { color: '#1a1f36', fontWeight: '800', fontSize: 13 },
    hotelRailMeta: { color: '#5f6b80', fontSize: 11, marginTop: 4 },
    selectedHotelBox: {
        backgroundColor: '#e6f7ef',
        borderWidth: 1,
        borderColor: '#b6e4c4',
        borderRadius: 10,
        padding: 10,
        marginBottom: 10,
    },
    selectedHotelName: { color: '#1a1f36', fontWeight: '800', marginBottom: 4 },
    selectedHotelStatic: { color: '#1f9d57', fontSize: 12, fontWeight: '800', marginTop: 2 },
    selectedHotelNotice: { color: '#1e6fe0', fontSize: 12, fontWeight: '700', marginTop: 6, marginBottom: 6 },
    successBox: {
        marginTop: 10,
        backgroundColor: '#e6f7ef',
        borderWidth: 1,
        borderColor: '#b6e4c4',
        borderRadius: 10,
        padding: 10,
        gap: 6,
    },
    successTitle: { color: '#1f9d57', fontWeight: '800', fontSize: 13 },
    successText: { color: '#2f6b43', fontSize: 12, lineHeight: 17 },
    errorText: {
        marginTop: 8,
        backgroundColor: '#fdecec',
        borderWidth: 1,
        borderColor: '#f5c6cf',
        borderRadius: 8,
        color: '#e5484d',
        paddingHorizontal: 10,
        paddingVertical: 8,
        fontSize: 12,
    },
    interToggleBtn: {
        backgroundColor: '#e8f1ff',
        borderWidth: 1,
        borderColor: '#bcd3f0',
        borderRadius: 10,
        paddingVertical: 12,
        alignItems: 'center',
    },
    interToggleBtnActive: {
        backgroundColor: '#fdecec',
        borderColor: '#e5484d',
    },
    interToggleText: { color: '#1e6fe0', fontWeight: '800', fontSize: 15 },
    interToggleTextActive: { color: '#e5484d' },
    faceConversationToggleBtn: {
        backgroundColor: '#e8f1ff',
        borderWidth: 1,
        borderColor: '#bcd3f0',
        borderRadius: 10,
        paddingVertical: 12,
        alignItems: 'center',
        marginBottom: 10,
    },
    faceConversationToggleBtnActive: {
        backgroundColor: '#e6f7ef',
        borderColor: '#19c37d',
    },
    faceConversationToggleText: { color: '#1e6fe0', fontWeight: '800', fontSize: 15 },
    faceConversationToggleTextActive: { color: '#1f9d57' },
    faceVadHintText: { marginTop: 8, marginBottom: 4, color: '#5f6b80', fontSize: 12, lineHeight: 18 },
    faceAiModeRow: { flexDirection: 'row', gap: 8, marginBottom: 10 },
    faceAiModeBtn: {
        flex: 1,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 10,
        paddingVertical: 10,
        alignItems: 'center',
    },
    faceAiModeBtnActive: { borderColor: '#1e6fe0', backgroundColor: '#e3f0ff' },
    faceAiModeText: { color: '#5f6b80', fontWeight: '800', fontSize: 14 },
    faceAiModeTextActive: { color: '#1e6fe0' },
    sorisaeQaPanel: {
        marginTop: 10,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#bcd3f0',
        borderRadius: 12,
        backgroundColor: '#ffffff',
        paddingHorizontal: 10,
        paddingVertical: 8,
    },
    sorisaeQaHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 6,
    },
    sorisaeQaHeaderText: { color: '#1e6fe0', fontWeight: '800', fontSize: 13 },
    sorisaeQaClearText: { color: '#5f6b80', fontWeight: '700', fontSize: 12 },
    sorisaeQaScroll: { maxHeight: 260 },
    sorisaeQaTurn: { marginBottom: 10 },
    sorisaeQaQuestionRow: { flexDirection: 'row', justifyContent: 'flex-start' },
    sorisaeQaAnswerRow: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 4 },
    sorisaeQaBubbleQuestion: {
        maxWidth: '82%',
        backgroundColor: '#eef2f8',
        borderRadius: 12,
        borderTopLeftRadius: 2,
        paddingHorizontal: 10,
        paddingVertical: 7,
    },
    sorisaeQaBubbleAnswer: {
        maxWidth: '82%',
        backgroundColor: '#e3f0ff',
        borderRadius: 12,
        borderTopRightRadius: 2,
        paddingHorizontal: 10,
        paddingVertical: 7,
    },
    sorisaeFab: {
        position: 'absolute',
        top: 0,
        left: 0,
        width: 58,
        height: 58,
        borderRadius: 29,
        backgroundColor: '#2a93ff',
        borderWidth: 2,
        borderColor: '#ffffff',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#1a2540',
        shadowOpacity: 0.25,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 3 },
        elevation: 8,
        zIndex: 999,
    },
    sorisaeFabIcon: { fontSize: 26 },
    sorisaeCallChip: {
        position: 'absolute',
        bottom: 18,
        alignSelf: 'center',
        paddingHorizontal: 16,
        paddingVertical: 9,
        borderRadius: 22,
        backgroundColor: '#ffffff',
        borderWidth: 1.5,
        borderColor: '#bcd3f0',
        shadowColor: '#1a2540',
        shadowOpacity: 0.18,
        shadowRadius: 5,
        elevation: 4,
    },
    sorisaeCallChipOn: {
        backgroundColor: '#e3f0ff',
        borderColor: '#1e6fe0',
    },
    sorisaeCallChipText: { color: '#1e6fe0', fontWeight: '800', fontSize: 13 },
    sorisaeWindowRoot: { flex: 1, backgroundColor: 'transparent', paddingHorizontal: 14 },
    sorisaeWindowHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 8,
        paddingBottom: 10,
    },
    sorisaeWindowTitle: { color: '#0b2e5e', fontWeight: '900', fontSize: 20 },
    sorisaeWindowCloseBtn: {
        paddingHorizontal: 12,
        paddingVertical: 7,
        borderRadius: 10,
        backgroundColor: '#e8f1ff',
    },
    sorisaeWindowCloseText: { color: '#1e6fe0', fontWeight: '800', fontSize: 13 },
    sorisaeWindowHint: { color: '#5f6b80', fontSize: 12, lineHeight: 18, marginBottom: 8 },
    sorisaeWindowStatus: { color: '#1e6fe0', fontSize: 13, fontWeight: '700', marginBottom: 8 },
    sorisaeWindowScroll: { flex: 1, borderTopWidth: 1, borderTopColor: '#dce6f2', paddingTop: 10 },
    sorisaeWindowEmpty: { color: '#8a93a3', fontSize: 14, textAlign: 'center', marginTop: 40 },
    sorisaeWindowFooter: {
        flexDirection: 'row',
        gap: 10,
        alignItems: 'center',
        paddingVertical: 12,
        borderTopWidth: 1,
        borderTopColor: '#dce6f2',
    },
    sorisaeWindowClearBtn: {
        paddingHorizontal: 14,
        paddingVertical: 12,
        borderRadius: 12,
        backgroundColor: '#e8f1ff',
    },
    sorisaeWindowClearText: { color: '#5f6b80', fontWeight: '800', fontSize: 13 },
    sorisaeWindowMicBtn: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 12,
        backgroundColor: '#e3f0ff',
        borderWidth: 1,
        borderColor: '#bcd3f0',
        alignItems: 'center',
    },
    sorisaeWindowMicBtnActive: { backgroundColor: '#e6f7ef', borderColor: '#19c37d' },
    sorisaeWindowMicText: { color: '#1e6fe0', fontWeight: '900', fontSize: 15 },
    sorisaeWindowMicTextActive: { color: '#1f9d57' },
    sorisaeWindowMicOrbWrap: {
        flex: 1,
        minHeight: 136,
        alignItems: 'center',
        justifyContent: 'center',
    },
    sorisaeWindowMicOrbAura: {
        position: 'absolute',
        width: 132,
        height: 132,
        borderRadius: 66,
        backgroundColor: 'rgba(70, 163, 255, 0.16)',
        borderWidth: 1.5,
        borderColor: 'rgba(30, 111, 224, 0.22)',
    },
    sorisaeWindowMicOrbBtn: {
        width: 96,
        height: 96,
        borderRadius: 48,
        backgroundColor: '#f8fbff',
        borderWidth: 2.5,
        borderColor: '#69aef5',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#1e3a66',
        shadowOpacity: 0.16,
        shadowRadius: 12,
        elevation: 5,
    },
    sorisaeWindowMicOrbBird: { fontSize: 42 },
    sorisaeWindowMicOrbText: {
        marginTop: 10,
        color: '#1f9d57',
        fontSize: 14,
        fontWeight: '900',
        letterSpacing: 0.2,
        textAlign: 'center',
    },
    sorisaeQaRoleLabel: { color: '#5f6b80', fontWeight: '800', fontSize: 11, marginBottom: 3 },
    sorisaeQaRoleLabelAnswer: { color: '#1e6fe0', fontWeight: '800', fontSize: 11, marginBottom: 3, textAlign: 'right' },
    sorisaeQaQuestionText: { color: '#1a1f36', fontSize: 14, lineHeight: 20 },
    sorisaeQaAnswerText: { color: '#1a1f36', fontSize: 14, lineHeight: 20, textAlign: 'right' },
    interPanel: {
        marginTop: 10,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: C.border,
        borderRadius: 10,
        padding: 10,
    },
    interStatus: {
        color: '#1e6fe0',
        fontSize: 13,
        marginBottom: 8,
    },
    loginOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: '#0009',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 16,
    },
    loginModal: {
        width: '100%',
        maxWidth: 420,
        backgroundColor: C.surface,
        borderWidth: 1,
        borderColor: C.border,
        borderRadius: 14,
        padding: 14,
    },
    // [f3] 로그인/회원가입 전용 풀스크린 화면.
    loginScreen: { flex: 1, backgroundColor: C.bg },
    loginScreenHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingTop: 14,
        paddingBottom: 4,
        backgroundColor: 'transparent',
    },
    loginScreenBrand: { color: '#1e6fe0', fontSize: 20, fontWeight: '900', letterSpacing: 0.3 },
    loginScreenClose: {
        width: 38,
        height: 38,
        borderRadius: 19,
        backgroundColor: 'rgba(255,255,255,0.7)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    loginScreenCloseText: { color: C.sub, fontSize: 17, fontWeight: '800' },
    loginScreenBody: {
        flexGrow: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 18,
        paddingVertical: 12,
    },
    loginHero: { alignItems: 'center', marginBottom: 14 },
    loginHeroMascot: { width: 168, height: 168 },
    loginHeroBrand: { color: '#0b2e5e', fontSize: 34, fontWeight: '900', letterSpacing: 0.2, marginTop: 2 },
    loginHeroTagline: { color: '#3a4356', fontSize: 14, fontWeight: '600', marginTop: 4 },
    loginCard: {
        width: '100%',
        maxWidth: 460,
        backgroundColor: C.surface,
        borderRadius: 22,
        padding: 20,
        shadowColor: '#1e3a66',
        shadowOpacity: 0.12,
        shadowOffset: { width: 0, height: 8 },
        shadowRadius: 22,
        elevation: 6,
    },
    loginFieldLabel: { color: '#1a1f36', fontSize: 14, fontWeight: '800', marginBottom: 7, marginTop: 4 },
    loginInputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f4f9ff',
        borderWidth: 1,
        borderColor: C.border,
        borderRadius: 14,
        paddingHorizontal: 12,
        marginBottom: 14,
    },
    loginInputIcon: { fontSize: 16, marginRight: 8, color: C.sub },
    loginInput: { flex: 1, color: C.text, fontSize: 15, paddingVertical: 13 },
    loginInputEye: { paddingHorizontal: 4, paddingVertical: 6 },
    loginInputEyeText: { fontSize: 17 },
    loginPrimaryBtn: {
        backgroundColor: '#1e6fe0',
        borderRadius: 26,
        paddingVertical: 15,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 2,
        shadowColor: '#1e6fe0',
        shadowOpacity: 0.3,
        shadowOffset: { width: 0, height: 5 },
        shadowRadius: 12,
        elevation: 4,
    },
    loginPrimaryBtnText: { color: '#ffffff', fontSize: 17, fontWeight: '900', letterSpacing: 0.3 },
    loginGoogleBtn: {
        backgroundColor: '#ffffff',
        borderRadius: 26,
        paddingVertical: 13,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#dce6f2',
    },
    loginGoogleBtnText: { color: '#1a1f36', fontSize: 16, fontWeight: '800' },
    loginOrDividerText: { color: C.sub, fontSize: 13, fontWeight: '600', textAlign: 'center', marginBottom: 12 },
    loginUtilityRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 16,
        paddingHorizontal: 2,
    },
    loginUtilityItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    loginUtilityIcon: { fontSize: 16, color: '#1e6fe0' },
    loginDivider: { height: 1, backgroundColor: C.border, marginTop: 16 },
    loginSignupRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, marginTop: 16 },
    loginSignupHint: { color: C.sub, fontSize: 14, fontWeight: '600' },
    loginSignupLink: { color: '#1e6fe0', fontSize: 14, fontWeight: '900' },
    loginDemoBtn: { alignItems: 'center', justifyContent: 'center', paddingVertical: 12, marginTop: 6 },
    loginDemoBtnText: { color: C.sub, fontSize: 13, fontWeight: '700', textDecorationLine: 'underline' },
    shareTargetModal: {
        width: '88%',
        maxWidth: 400,
        backgroundColor: '#ffffff',
        borderRadius: 22,
        padding: 18,
        borderWidth: 1,
        borderColor: '#dce6f2',
        gap: 12,
    },
    shareTargetHint: { color: C.sub, fontSize: 13, lineHeight: 19 },
    shareTargetList: { gap: 10 },
    shareTargetBadgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    shareTargetCard: {
        gap: 4,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#dce6f2',
        backgroundColor: '#ffffff',
        padding: 14,
    },
    shareTargetTitle: { color: '#1a1f36', fontSize: 14, fontWeight: '800' },
    shareTargetMeta: { color: '#1e6fe0', fontSize: 12, fontWeight: '700' },
    shareTargetPreview: { color: '#3a4356', fontSize: 12, lineHeight: 18 },
    mediaMetaCard: {
        flexDirection: 'row',
        gap: 12,
        alignItems: 'center',
        marginTop: 8,
        marginBottom: 8,
        padding: 12,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#dce6f2',
        backgroundColor: '#f4f9ff',
    },
    mediaThumbBox: {
        width: 64,
        height: 64,
        borderRadius: 14,
        backgroundColor: '#e3f0ff',
        borderWidth: 1,
        borderColor: '#bcd3f0',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 2,
    },
    mediaThumbEmoji: { fontSize: 24 },
    mediaThumbCaption: { color: '#1e6fe0', fontSize: 10, fontWeight: '800' },
    mediaMetaBody: { flex: 1, gap: 6 },
    mediaMetaTitle: { color: '#1a1f36', fontSize: 13, fontWeight: '800' },
    mediaBadgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    mediaBadge: {
        borderRadius: 999,
        backgroundColor: '#e3f0ff',
        paddingHorizontal: 10,
        paddingVertical: 5,
    },
    mediaBadgeText: { color: '#1e6fe0', fontSize: 11, fontWeight: '800' },
    loginModalTitle: { color: '#1e6fe0', fontSize: 17, fontWeight: '800', marginBottom: 10 },
    loginModeHint: { color: C.sub, fontSize: 12, lineHeight: 18, marginBottom: 10 },
    signupProfileLabel: { color: '#1a1f36', fontSize: 12, fontWeight: '800', marginBottom: 6 },
    signupChannelRow: { flexDirection: 'row', gap: 8, marginBottom: 8 },
    signupChannelBtn: {
        flex: 1,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#dce6f2',
        backgroundColor: '#ffffff',
        paddingVertical: 10,
        alignItems: 'center',
    },
    signupChannelBtnActive: {
        borderColor: '#1e6fe0',
        backgroundColor: '#e3f0ff',
    },
    signupChannelBtnText: { color: '#3a4356', fontSize: 12, fontWeight: '700' },
    signupPickerTrigger: {
        minHeight: 58,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#dce6f2',
        backgroundColor: '#f4f9ff',
        paddingHorizontal: 14,
        paddingVertical: 12,
        marginBottom: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    signupPickerValue: { color: '#1a1f36', fontSize: 14, fontWeight: '800' },
    signupPickerMeta: { color: '#5f6b80', fontSize: 11, marginTop: 4 },
    signupPickerHint: { color: '#1e6fe0', fontSize: 12, fontWeight: '800' },
    signupModalSub: { color: '#5f6b80', fontSize: 12, lineHeight: 18, marginTop: -4, marginBottom: 12 },
    signupProfileHint: { color: '#5f6b80', fontSize: 12, lineHeight: 18, marginTop: -2, marginBottom: 8 },
    authModeToggleBtn: {
        alignSelf: 'flex-start',
        marginTop: 2,
        marginBottom: 4,
        paddingVertical: 6,
    },
    authModeToggleText: { color: '#1e6fe0', fontSize: 13, fontWeight: '700' },
    modalActionRow: { flexDirection: 'row', gap: 8, marginTop: 6 },
    contactPickerList: { maxHeight: 320, marginTop: 8 },
    contactPickerListBody: { gap: 8, paddingBottom: 4 },
    contactPickerRow: {
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#dce6f2',
        backgroundColor: '#ffffff',
        paddingHorizontal: 12,
        paddingVertical: 12,
        gap: 4,
    },
    contactPickerName: { color: '#1a1f36', fontSize: 14, fontWeight: '800' },
    contactPickerMeta: { color: '#5f6b80', fontSize: 12 },
    contactPickerEmpty: { color: '#5f6b80', fontSize: 12, paddingVertical: 12 },
    modalMainBtn: { flex: 1 },
    modalCloseBtn: {
        flex: 1,
        backgroundColor: C.surface,
        borderWidth: 1,
        borderColor: C.border,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    voipModalOverlay: {
        flex: 1,
        backgroundColor: 'transparent',
        padding: 0,
        justifyContent: 'center',
    },
    voipModalCard: {
        flex: 1,
        borderRadius: 0,
        overflow: 'hidden',
        borderWidth: 0,
        borderColor: 'transparent',
        backgroundColor: 'transparent',
    },
    voipLobbyWrap: { flex: 1 },
    voipLobbyScroll: { flex: 1 },
    voipLobbyBody: { paddingHorizontal: 18, paddingBottom: 22 },
    voipProfileCard: {
        borderWidth: 1,
        borderColor: '#dce6f2',
        backgroundColor: '#ffffff',
        borderRadius: 14,
        padding: 16,
        marginBottom: 14,
    },
    voipProfileTitle: { color: '#0b2e5e', fontSize: 22, fontWeight: '900', marginBottom: 10 },
    voipProfileMeta: { color: '#3a4356', fontSize: 14, lineHeight: 22, marginBottom: 4 },
    voipLobbySectionLabel: { color: '#5f6b80', fontSize: 12, fontWeight: '800', marginBottom: 8 },
    voipGenderRow: { flexDirection: 'row', gap: 8, marginBottom: 14 },
    voipGenderChip: {
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: '#dce6f2',
        backgroundColor: '#ffffff',
    },
    voipGenderChipActive: { borderColor: '#1e6fe0', backgroundColor: '#e3f0ff' },
    voipGenderChipText: { color: '#3a4356', fontSize: 12, fontWeight: '700' },
    voipGenderChipTextActive: { color: '#1e6fe0' },
    voipLobbyActionRow: { flexDirection: 'row', gap: 10, flexWrap: 'wrap', marginTop: 8 },
    voipLobbyLoading: { marginTop: 8 },
    voipStatusBanner: {
        marginTop: 10,
        padding: 10,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#f5c2c7',
        backgroundColor: '#fff5f5',
        gap: 6,
    },
    voipStatusBannerText: { color: '#5f6b80', fontSize: 12, lineHeight: 17 },
    voipValidationExitCard: {
        marginTop: 10,
        padding: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#c9daf8',
        backgroundColor: '#f0f6ff',
        gap: 8,
    },
    voipValidationExitTitle: { color: '#0b2e5e', fontSize: 14, fontWeight: '800' },
    voipValidationExitSub: { color: '#5f6b80', fontSize: 12, lineHeight: 17 },
    voipValidationBypassBtn: {
        alignSelf: 'flex-start',
        paddingVertical: 10,
        paddingHorizontal: 14,
        borderRadius: 10,
        backgroundColor: '#2563eb',
    },
    voipValidationBypassBtnText: { color: '#ffffff', fontSize: 13, fontWeight: '800' },
    voipValidationExitOffBtn: {
        alignSelf: 'flex-start',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 9,
        borderWidth: 1,
        borderColor: '#bcd3f0',
    },
    voipValidationExitOffBtnText: { color: '#1e6fe0', fontSize: 12, fontWeight: '700' },
    voipLobbyModeText: { color: '#5f6b80', fontSize: 12, fontWeight: '700', marginTop: 6, marginBottom: 12 },
    voipLobbyFlowHint: { color: '#3a4356', fontSize: 12, lineHeight: 18, marginBottom: 8 },
    voipLobbyPstnHint: { color: '#5f6b80', fontSize: 12, lineHeight: 18, maxWidth: 560 },
    voipAuditCard: {
        marginTop: 16,
        borderWidth: 1,
        borderColor: '#dce6f2',
        backgroundColor: '#ffffff',
        borderRadius: 14,
        padding: 14,
        gap: 8,
    },
    voipAuditHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
    voipAuditTitle: { color: '#1a1f36', fontSize: 15, fontWeight: '800' },
    voipAuditHint: { color: '#5f6b80', fontSize: 11, lineHeight: 16 },
    voipAuditEventRow: {
        backgroundColor: '#f4f9ff',
        borderWidth: 1,
        borderColor: '#dce6f2',
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 8,
        gap: 3,
    },
    voipAuditEventTitle: { color: '#1a1f36', fontSize: 12, fontWeight: '800' },
    voipAuditEventMeta: { color: '#5f6b80', fontSize: 11, lineHeight: 16 },
    voipAuditEmptyText: { color: '#5f6b80', fontSize: 12, lineHeight: 18 },
    voipModalTitle: { color: '#0b2e5e', fontSize: 20, fontWeight: '900', marginBottom: 8 },
    voipModalSub: { color: C.sub, fontSize: 13, lineHeight: 18, marginBottom: 12 },
    footer: { marginTop: 30, alignItems: 'center' },
    footerText: { color: C.sub, fontSize: 11, textAlign: 'center', lineHeight: 18 },
    dataSourcesLink: { marginTop: 8, paddingVertical: 4, paddingHorizontal: 8 },
    dataSourcesLinkText: { color: '#1e6fe0', fontSize: 12, fontWeight: '700', textDecorationLine: 'underline' },
    modalCloseRow: { flexDirection: 'row', justifyContent: 'flex-end', padding: 10 },
    friendModalCloseBtn: { paddingHorizontal: 12, paddingVertical: 6, backgroundColor: '#e8f1ff', borderRadius: 8 },
    friendModalCloseBtnText: { color: '#94a3b8', fontSize: 13 },
    friendModalBody: { flex: 1, minHeight: 0 },
});
